In [1]:
import dart_fss as dart_fss
import pandas as pd

Error occurred during getting browser(s): random, but was suppressed with fallback.

In [2]:
api_key = '여기에 API 키를 입력'
dart_fss.set_api_key(api_key="79985b0c504cc0bb5fce093fba4fd0be634e04a5")

corp_list = dart_fss.get_corp_list()

corp_list.corps

[[00434003]다코,
 [00430964]굿앤엘에스,
 [00388953]크레디피아제이십오차유동화전문회사,
 [00179984]연방건설산업,
 [00420143]브룩스피알아이오토메이션잉크,
 [00401111]매경아이비아이,
 [00435534]캐드뱅크,
 [00430186]엠와이오피삼차유동화전문유한회사,
 [00430201]엠와이오피이차유동화전문유한회사,
 [00430210]엠와이오피일차유동화전문유한회사,
 [00430229]포스미디어,
 [00140432]축복할렐루야,
 [00426208]한국전자화학,
 [00433262]ConnachtCapitalMarketInvestmentLtd.,
 [00433749]선진아이티,
 [00433785]팀스코리아,
 [00196079]에넥스하이테크,
 [00435048]세이스텝바이스텝혼합형펀드,
 [00435057]유리알파헷지채권혼합형펀드,
 [00108843]한기술정보통신,
 [00443232]다움종합건설,
 [00248293]한국애치슨,
 [00455662]고은상사,
 [00149318]조흥종합건설,
 [00451347]유니즈유통,
 [00415105]창대화장품,
 [00420824]문화종합건설,
 [00389439]한국종합미디어,
 [00454016]아이펜텍,
 [00452072]대홍염공,
 [00437602]지오항공여행사,
 [00365518]헤이아니타코리아,
 [00246967]태산산업개발,
 [00445559]군포종합시장,
 [00444657]기우,
 [00448936]라시도,
 [00405658]예전미디어,
 [00410818]세미가,
 [00416061]대닉스,
 [00448909]인포핸드,
 [00445407]지현개발,
 [00421647]한국부동산신탁제일차유동화전문유한회사,
 [00421425]ISCCaymanLtd.,
 [00423265]연산,
 [00423292]씨케이알유동화전문유한회사,
 [00420602]디에스피,
 [00307505]LOMBARDKOREAILIMITED,
 [00241397]우신투자자문,
 [00421896]외환카드제오차유동화전문유한회사,
 [00365712]태연,
 [00388616]글로벌금강제일차유동화전문유한회사,
 [00230407]글로벌렌탈,
 [00423566]뤼미에르에셋,
 [00423274]바사라엔터테인먼트,
 [00419688]대백유동화전문유한회사,
 [00419712]아이키키,
 [00414665]진명씨앤씨,
 [00421869]한경핫벤처,
 [00421957]우리부동산제일차유동화전문유한회사,
 [00255442]영진상운,
 [00427517]한국토지신탁제오차유동화전문유한회사,
 [00376152]다드림커뮤니케이션,
 [00382241]ARISAIGASIANSMALLCOMPANIESFUND(L)BHD,
 [00431501]싱가포르개발은행서울지점,
 [00434289]KTB혼합형펀드,
 [00434298]KTB플러스찬스혼합형펀드,
 [00434313]KTB포트폴리오스타혼합형펀드,
 [00434322]KTB에버스타혼합형펀드,
 [00429463]나노이앤씨,
 [00429515]지산엔터프라이즈,
 [00432175]유아이에스코리아,
 [00387033]트리플에스유동화전문유한회사,
 [00384045]크레디피아제이십일차유동화전문유한회사,
 [00431608]싱가포르개발은행,
 [00431705]엘지팩토링제일차유동화전문유한회사,
 [00430256]이피에스뱅크,
 [00431167]이라이프네트워크,
 [00432315]덕성,
 [00413134]타오건설,
 [00435376]장원코리아,
 [00110909]대신통상,
 [00220695]서울교육,
 [00211794]보성패션,
 [00454496]넥스탑,
 [00455592]마니빌,
 [00370796]제이엘코프,
 [00199401]컴마을,
 [00369596]삼신크리에이션,
 [00210078]호한통상,
 [00363398]케이엠티,
 [00110042]대백가구,
 [00364324]청빛산업개발,
 [00248017]삼양전자,
 [00452179]숭민코리아유통,
 [00413754]유오티앤씨,
 [00343163]한라스페코중공업,
 [00452513]알본,
 [00435978]상일디지털,
 [00368153]서전어패럴,
 [00455149]웰비스트랜스,
 [00249946]한국키엔스,
 [00110839]대신생명보험,
 [00293798]대성메디테크,
 [00113119]대한알루미늄공업,
 [00424389]남성엠케이,
 [00424486]씨엠액텍,
 [00224734]한국부동산신탁,
 [00197713]주은산업,
 [00421948]신엘지프라이머리제이차유동화전문유한회사,
 [00422381]데코제일차유동화전문유한회사,
 [00350446]뉴스테이트삼차모기지유동화전문유한회사,
 [00396642]엘지수퍼센터,
 [00425449]아이클릭세븐,
 [00425458]월드인코레스,
 [00425333]코리아픽시컴,
 [00424617]산은부동산제사차유동화전문유한회사,
 [00424006]글로벌자이언트시스템,
 [00424051]신클레어,
 [00403599]에이에스피기업구조조정전문,
 [00425519]Marubeni-ItochuSteelInc.,
 [00224585]신한,
 [00429524]우리모아제이차유동화전문유한회사,
 [00429533]글로벌사모안정혼합형펀드,
 [00432722]파워외환카드제팔차유동화전문유한회사,
 [00432786]파워외환카드제오차유동화전문유한회사,
 [00429728]영퓨처,
 [00428668]코로볼틴펀드리미티드,
 [00430751]대창크랑크,
 [00385372]허츠제일차유동화전문유한회사,
 [00431680]새암교육,
 [00386308]반지종합상가,
 [00256450]동서산업건설(가칭),
 [00290816]대우종합기계(가칭),
 [00291532]대우조선공업(가칭),
 [00127990]삼일상호저축은행,
 [00431565]케이디에스에스,
 [00399959]비젼케이파트너스,
 [00430238]리버랜드,
 [00263034]동양선재,
 [00205298]춘천미도파,
 [00431042]거버너스M&A사모펀드3호,
 [00348715]아이앤비골드문브이에이치,
 [00447964]체리미디어,
 [00448361]경원하이텍,
 [00185851]중원화학,
 [00445735]나크나인,
 [00385770]동남해상관광호텔,
 [00319245]한성선박,
 [00126502]삼성콘크리트공업,
 [00363440]엠알더블유테크노로지,
 [00445522]제이에이치홀딩스,
 [00320302]동연산업,
 [00444958]우양주택건설,
 [00441836]해진하우징,
 [00445629]효헌산업,
 [00454052]우림산업개발,
 [00454414]에이스하이테크,
 [00196857]해표푸드서비스,
 [00413383]에프씨산업,
 [00225098]극동뉴메릭,
 [00410304]서울드림랜드,
 [00310998]한국미라이공업,
 [00415114]21세기화장품,
 [00451000]광명산업,
 [00369985]다음솔루션,
 [00371670]정우조명,
 [00401430]모바일웰컴,
 [00247027]푸른건설,
 [00144058]월다크,
 [00416867]길도건업,
 [00456263]원일스포지움,
 [00436339]용인자원,
 [00120748]마산강관,
 [00386724]세창철강공업,
 [00255390]재무와정보,
 [00455547]대양중공업,
 [00233398]이에이지씨,
 [00405065]페타코페트로륨,
 [00425537]MarubeniCorporation,
 [00424158]캐피탈라인,
 [00100920]건설증권,
 [00370167]일진전자통신,
 [00409131]오픈솔루션,
 [00424194]AMERICAORIENTALGROUP,
 [00364713]mvp창업투자,
 [00408901]라이져,
 [00161170]한라시멘트,
 [00423557]한국알리안츠화재해상보험,
 [00307444]코리아벌처투자,
 [00370468]티에스케이지,
 [00424219]텔레닉스,
 [00424185]유니텍워터시스템즈,
 [00424556]거륜씨앤씨,
 [00121631]문화,
 [00424866]모비도미,
 [00424884]에이치케이인베스트먼트유동화전문유한회사,
 [00424927]LiquidmetalTechnologies,
 [00423797]모멘타(케이만),
 [00433350]KTB프라임8호혼합형사모펀드,
 [00433369]유리명품장기채권형사모펀드3호,
 [00433378]유리유니콘채권혼합형펀드,
 [00433387]맥쿼리아이엠엠프라임7호채권형사모펀드,
 [00433420]마이에셋애국성장형이호펀드,
 [00433457]채권플러스알파2호펀드,
 [00433466]마이다스사모프라임안정형2호펀드,
 [00376073]테크포인트,
 [00234306]부국개발,
 [00429418]세닥에듀케이션,
 [00429977]에이치엘홀딩스에스에이,
 [00340786]크레디리요네증권,
 [00218928]케이티인더스트리,
 [00106793]김천상호저축은행,
 [00378886]이화홀딩스,
 [00433484]미래에셋유니온사모혼합형펀드2호,
 [00433493]맥쿼리아이엠엠액티브채권형사모펀드3호,
 [00433509]맥쿼리아이엠엠프라임6호혼합형사모펀드,
 [00433518]유리명품장기채권형사모펀드2호,
 [00406596]신우쉬핑,
 [00443001]동흥컨설팅,
 [00363741]디조콤,
 [00436375]맘모스산업개발,
 [00222277]아성,
 [00446284]디토정보기술,
 [00446682]오우디앤씨,
 [00139995]에어웨이엑스프레스,
 [00444602]탑월드,
 [00150314]진로종합유통,
 [00231840]케이에프텍,
 [00236243]나토상사,
 [00309479]지오이네트,
 [00447034]이십일세기종합건설,
 [00447496]일현건설,
 [00300928]삼영기공,
 [00317566]삼능주택,
 [00412001]동해,
 [00155407]풍광직물,
 [00443542]기성텍스타일,
 [00179726]제텍스바론,
 [00300982]국제개발,
 [00298818]유유후마킬라,
 [00424644]피앤씨미디어,
 [00350570]비앤에프투자자문,
 [00424316]한국부동산신탁제이차유동화전문유한회사,
 [00368551]에이텍,
 [00424307]덕경종합건설,
 [00425078]글로벌스페셜혼합형사모펀드,
 [00154499]태화,
 [00424653]씨앤앰유동화전문유한회사,
 [00414522]온누리방송,
 [00425120]케이티엠,
 [00356723]아이앤비골드문컨설팅,
 [00375506]동국제강제일차유동화전문유한회사,
 [00424769]밸류노믹스기업구조조정전문회사,
 [00223300]조창,
 [00360294]영지통상,
 [00425209]RosewellConsulting&InvestmentLtd.,
 [00433527]유리시티즌장기채권형사모펀드,
 [00433536]KTB장기채권형사모펀드3호,
 [00433545]KTB장기채권형사모펀드4호,
 [00433554]맥쿼리아이엠엠포세이돈채권형사모펀드4호,
 [00433563]마이에셋애국안정형1호펀드,
 [00434702]노보스,
 [00434711]세이유니온채권혼합형사모펀드,
 [00434720]LG드림혼합형펀드,
 [00434739]알파그로스주식형펀드,
 [00434748]유리알파헷지채권혼합형사모펀드,
 [00434757]알파헷지이기욱혼합형펀드,
 [00434775]맥쿼리IMM홀인원채권형펀드,
 [00434793]유리시장중립채권형사모펀드,
 [00434809]유리알파30채권혼합형사모펀드,
 [00432573]파워외환카드제사차유동화전문유한회사,
 [00432607]파워외환카드제이차유동화전문유한회사,
 [00432643]케드제이차유동화전문유한회사,
 [00323390]굿윌경영자문,
 [00412861]국제금속산업,
 [00443913]덕정무역,
 [00315179]삼성코닝마이크로옵틱스,
 [00165264]혜성건설,
 [00368171]코스모에쿼티파트너스,
 [00369480]경빈,
 [00446196]내외시스템,
 [00108311]태승어패럴,
 [00105615]금동조명,
 [00360197]태광정밀공업,
 [00360364]게르마니셀로이드코리아,
 [00366720]청우제강,
 [00273536]필리아텔레콤,
 [00443375]진도개발,
 [00447511]만남과축복,
 [00403872]영상산업,
 [00441757]쌈솔,
 [00445221]링크테크21,
 [00448769]건화메디팜,
 [00351357]윈윈창업투자,
 [00371333]지티웹코리아,
 [00392716]트랜스미디어매니지먼트,
 [00424398]남성유통,
 [00380322]무지개유동화전문유한회사,
 [00387264]엘지화학제일차유동화전문유한회사,
 [00425379]페가수스캐피탈아시아,
 [00421595]한솔케미언스제일차유동화전문유한회사,
 [00128564]삼천리M&C,
 [00304757]넥스트디앤드에스,
 [00407142]드림라인제일차유동화전문유한회사,
 [00408044]동국산업제일차유동화전문유한회사,
 [00112387]휴먼이노텍,
 [00423539]자도,
 [00103981]광전자INT,
 [00416478]굿케이디비제삼차유동화전문유한회사,
 [00418801]신엑스퍼트유동화전문,
 [00419332]비발디제일차유동화전문유한회사,
 [00418078]두산위브유동화전문유한회사,
 [00419651]코오롱폴리스유동화전문유한회사,
 [00251695]메디캐피탈,
 [00432661]파워외환카드제삼차유동화전문유한회사,
 [00430858]에이치에스비프로퍼티원인베스트먼트유동화전문유한회사,
 [00432670]서상금속,
 [00434827]세이한가족주식형펀드,
 [00434872]알파크레디트플러스채권형펀드,
 [00434881]알파국공채채권형사모펀드,
 [00434906]세이에이스알파혼합형펀드,
 [00434915]맥쿼리IMM코리아플러스채권형펀드,
 [00434924]맥쿼리IMM마켓뉴트럴혼합형사모펀드,
 [00434933]세이원채권형펀드,
 [00435093]그레이터차이나1호사모펀드,
 [00435109]윌러스,
 [00431820]디베스트사모엠엔에이펀드일호,
 [00398525]미래에셋프리미어전환혼합형이호펀드,
 [00260967]디지텔,
 [00378956]유리세이프롱숏채권혼합형펀드,
 [00164104]리젠트화재보험,
 [00101266]경남리스금융,
 [00412834]굿머니,
 [00226343]한소닉테크,
 [00150147]지산개발,
 [00416937]지구환경산업,
 [00132497]성도통상,
 [00216461]에프샵,
 [00369301]근영전자통신,
 [00360106]보해주정,
 [00410483]윈스텍,
 [00409928]조한도시개발,
 [00209647]대웅전기산업,
 [00370316]해피라인,
 [00134246]세원건설,
 [00444806]린나이씨에스,
 [00233112]성우전자,
 [00450986]미도산업개발,
 [00442206]덕성섬유,
 [00361664]기흥종합건설,
 [00370334]이에이치상사,
 [00432616]웨이브티브이,
 [00405436]유니크,
 [00414319]송학장갑,
 [00261610]위트비전,
 [00362432]월드무역,
 [00415293]오픈테크,
 [00413204]아피아,
 [00413277]차세대정보통신,
 [00268455]조흥신탁유동화전문회사,
 [00273606]오토일천구백구십구의일유동화전문유한회사,
 [00303369]한국토지신탁제이차유동화전문유한회사,
 [00317043]포커스제1차유동화전문유한회사,
 [00328517]베스트이지제일차유동화전문유한회사,
 [00341776]모비스코람유동화전문유한회사,
 [00362131]아이에스피,
 [00427492]한실흥산,
 [00363413]아이티엔방송,
 [00302829]슈퍼데크코리아,
 [00426758]산은부동산제오차유동화전문유한회사,
 [00427474]덕화산업,
 [00428695]국민카드이천이의일유동화전문유한회사,
 [00366508]마일스톤벤처투자,
 [00402208]에스비아이코리아,
 [00175021]씨티은행,
 [00429250]AllianzFinanceB.V.,
 [00425777]동의보감유동화전문유한회사,
 [00109125]세화기술투자,
 [00388810]미래에셋프리미어혼합형펀드,
 [00383426]마이다스차익거래안정혼합형펀드,
 [00146676]아이씨켐,
 [00338152]소프트윈,
 [00438902]신하나로유동화전문유한회사,
 [00432856]벽산건설블루밍제일차유동화전문유한회사,
 [00431033]이천일아울렛제일차유동화전문유한회사,
 [00240866]씨마유통,
 [00440934]캠앤아이코리아,
 [00440952]제이경영컨설팅,
 [00435598]태거산업,
 [00350136]마인드텔,
 [00350206]엘파오벤쳐캐피탈,
 [00268288]심스밸리,
 [00105846]LGEI,
 [00350756]유리크레디트회사채혼합형펀드,
 [00149497]알파캐피탈,
 [00264778]유니씨앤티,
 [00289227]미래에셋파이오니어벤처코스닥펀드,
 [00449184]디에이치파트너스,
 [00369028]근하종합개발호텔엑스포,
 [00152491]코락,
 [00445601]터보엔지니어링,
 [00407610]알파엔지니어링,
 [00146241]명성건설,
 [00446071]스카이함백,
 [00368384]비에스그룹,
 [00446840]삼부이엔씨,
 [00245791]두앙종합건설,
 [00449625]신성전자,
 [00375223]한국기업금융자문,
 [00411631]고룡,
 [00256326]아성식품,
 [00367330]세원지애에이치,
 [00371838]남양주택건설,
 [00246480]이조해운,
 [00359304]한서화학,
 [00415600]대륭전자,
 [00422910]서울에프엔텍파트너스,
 [00451055]팔공산온천관광호텔,
 [00448839]택산개발,
 [00234670]동진피엠씨,
 [00224707]대흥정공,
 [00193568]신대광주택,
 [00415080]아프로시스템스,
 [00415053]화진코스메틱,
 [00414869]모비야,
 [00365527]우리켐테크,
 [00364245]ABC,
 [00364005]캐피탈아거스,
 [00413329]유니솔,
 [00215222]세화유통,
 [00252481]용강,
 [00369897]기바전자,
 [00310855]에프에스비티아이코리아,
 [00370015]디지텍,
 [00303448]알에이코프,
 [00404394]매경휴스닥,
 [00201946]한국이연,
 [00304207]한원텔레콤,
 [00305093]진우,
 [00410720]탑종합건설,
 [00354354]썬키스,
 [00311049]위슬런,
 [00412782]대산반도체,
 [00426615]네오소프트,
 [00164061]드림에스디,
 [00381659]크레디피아제십구차유동화전문,
 [00382959]콩코드캐피탈아시아,
 [00118886]에이브이씨닷컴,
 [00374835]케이씨알파트너스,
 [00115700]동성투자,
 [00389192]오엔씨네트웍스,
 [00346452]씨에스지,
 [00420356]하이페리온제이차유동화전문유한회사,
 [00425528]부산유조선,
 [00427784]목동우림루미아트유동화전문유한회사,
 [00244297]천보파이낸스,
 [00428817]나라펫,
 [00425740]하이케어시스템즈,
 [00389086]우리금융제일차유동화전문유한회사,
 [00425759]키치녹스,
 [00426721]에이치에스제일차유동화전문유한회사,
 [00426651]신드림풀유동화전문유한회사,
 [00427951]넥센캐피탈,
 [00448112]종연산업,
 [00446655]성환,
 [00357111]삼두디엔에스,
 [00193221]삼희산업,
 [00407595]아이스타뮤직,
 [00367075]신흥울테크,
 [00448501]삼양이컴,
 [00197856]전주코아호텔,
 [00378017]헬리오스기업구조조정전문회사,
 [00207384]동일상사,
 [00233927]헨켈코리아,
 [00255372]센텍,
 [00246693]태흥기업,
 [00367932]만적,
 [00334341]성신무역,
 [00190224]새한철강,
 [00448291]한림종합개발,
 [00445391]동방귀석,
 [00169321]부곡관광,
 [00434076]에이취.엠.에스,
 [00205128]서통테크놀로지,
 [00450250]한경섬유,
 [00368126]세진티앤엠,
 [00175386]경기교통,
 [00205748]강호개발,
 [00358378]만덕,
 [00221409]한국어센셜소프트웨어,
 [00414328]와우북,
 [00409982]부풍,
 [00134149]세우무역,
 [00414461]신우종합건설,
 [00304508]중원,
 [00247753]아스트로,
 [00368816]한국멀티넷,
 [00366085]넥스트미디어아이,
 [00412302]일성리조트,
 [00387246]동광산건,
 [00265050]유렉셀테크놀러지,
 [00236182]성일컴퓨텍,
 [00296555]엠에프씨,
 [00327226]얼라이언스시스템,
 [00412852]대한주택이앤지,
 [00143970]원창판지,
 [00301404]한국피시,
 [00109541]대륙공업,
 [00404880]디지털테크놀러지,
 [00393858]드림데이타,
 [00385123]리첸시아유동화전문유한회사,
 [00429010]코리아페이넷,
 [00424963]디더블유씨유동화전문유한회사,
 [00425768]티지일차유동화전문유한회사,
 [00426749]피앤지정보통신,
 [00330415]인바인,
 [00150794]진흥주택,
 [00429038]굿앤세이프,
 [00421081]디바이너,
 [00361734]케이아이티창업투자,
 [00388768]외환카드제사차유동화전문유한회사,
 [00425421]오프마이십일,
 [00421850]창신테크,
 [00425315]파워엑시스,
 [00427580]삼성프론티어제십이차유동화전문유한회사,
 [00425218]쓰리엔제이차유동화전문유한회사,
 [00106951]낙산관광호텔,
 [00395661]현지개발,
 [00275118]케이티비벤처벌처일호펀드,
 [00295389]메타텍,
 [00389147]골든보우창업투자,
 [00126803]삼아,
 [00242341]에스엠아이씨,
 [00440314]오토피아제팔차유동화전문유한회사,
 [00440332]니즈솔루션,
 [00441322]이나라카드,
 [00440165]히타치전선,
 [00288884]미래에셋드림파이오니어펀드,
 [00148452]GPS,
 [00156017]하나은행,
 [00261045]시스컴,
 [00437532]개풍주택개발,
 [00303095]지오스테크널러지,
 [00438753]IndusAsiaPacificFund,Ltd.,
 [00367464]지앤텍,
 [00201955]금화냉동,
 [00409849]혜성,
 [00131443]서통상사,
 [00174022]유창섬유,
 [00444763]피프,
 [00412171]모수인터내쇼날,
 [00232973]동해산업,
 [00152419]대농중공업,
 [00257413]신영팩토링,
 [00362511]승진건설,
 [00446743]아워스인베스트먼트,
 [00253055]태흥산업개발,
 [00448714]마하인더스트리,
 [00448705]모아건설,
 [00101716]경북레미콘,
 [00447876]그루빅,
 [00448671]라이프건설,
 [00217150]대진종합건설,
 [00164344]해피아이,
 [00303314]성서,
 [00451213]한신공업,
 [00407416]오랙스정유,
 [00178675]이논,
 [00367181]예들,
 [00413514]가인수산,
 [00127538]삼원산업,
 [00370051]유덕건설,
 [00415123]크로스전자,
 [00106012]금성텔,
 [00158495]한국아프라이드매그네틱스,
 [00299774]스타럽스,
 [00414911]텔레프리,
 [00414762]금화도시개발,
 [00234078]길정종합건설,
 [00412515]메디링스,
 [00151076]창원개발,
 [00170512]우신레저산업,
 [00370033]연이산업,
 [00406587]다른신문,
 [00413471]비투올네트,
 [00248804]성진사,
 [00359854]네투스테크놀러지,
 [00252870]동구,
 [00300432]비아이캐피탈,
 [00415938]세아개발,
 [00345693]SKIMT,
 [00426226]일신제약,
 [00426235]모아에셋,
 [00376505]그린페이퍼텍,
 [00427058]원업제이차유동화전문유한회사,
 [00427100]두손테크피아,
 [00427331]유니맥코리아,
 [00429144]아하크레딧유동화전문유한회사,
 [00429180]거버너스M&A사모펀드2호,
 [00419916]기가솔,
 [00421009]모쿠스,
 [00363796]남양산업,
 [00302148]에이팩스기술투자,
 [00426314]에스지테크놀러지,
 [00427146]도이체방크아게런던,
 [00245065]에이에스엠엘에스씨,
 [00427182]얼라이언스캐피탈파트너즈,
 [00382852]대진산업,
 [00362113]하늘사랑,
 [00220756]씨앤씨캐피탈,
 [00162319]한양상사,
 [00355511]Photronics,Inc.,
 [00400176]무빙넷,
 [00396402]슈마커코리아,
 [00439938]유케이,
 [00337977]캐피탈리서치앤매니지먼트컴퍼니,
 [00436047]월드타운,
 [00387097]센텀파크유동화전문유한회사,
 [00274410]인트빔,
 [00328100]나래소프트시스템,
 [00243845]삼광고하켐,
 [00336260]OAKMARKINTERNATIONALFUND,
 [00262026]신중앙99-1유동화전문유한회사,
 [00264431]크레디피아유동화전문,
 [00264495]중소기업유동화전문유한회사,
 [00267067]산은캐피탈제일호유동화전문유한회사,
 [00290791]국민제이차유동화전문회사,
 [00297837]국민제일차유동화전문유한회사,
 [00429162]남양씨앤씨,
 [00203643]유일냉장,
 [00450108]평산공영,
 [00171414]파산자한국산업증권,
 [00200549]대홍방직,
 [00114543]도투락,
 [00197607]해덕기업,
 [00258263]이수금속,
 [00363617]세미코리아,
 [00450287]정방종합건설,
 [00413082]성우종합건설,
 [00449537]신아토건,
 [00163071]한일염공,
 [00453239]코스모건설,
 [00414267]한국방송출판,
 [00349088]태성개발,
 [00451514]월성주택건설,
 [00386830]심도산업,
 [00410128]코리아라이닝,
 [00161198]한라종합건설,
 [00126849]삼안공영,
 [00437824]제석주택,
 [00363176]한국모빌솔루션,
 [00299871]연화상사,
 [00340892]한강온천,
 [00415725]나우아이엔에스,
 [00306205]디아이씨,
 [00371351]비앤에스아이엔씨,
 [00369851]창원건설,
 [00415840]알루테크,
 [00246666]대상하이디어,
 [00153296]태강산업,
 [00161268]한륙전자,
 [00210476]영신산업,
 [00365581]이사이트랩,
 [00183598]영신플랜트,
 [00417088]정연산업,
 [00415062]아코텔레콤,
 [00172529]대영,
 [00407337]프라임플러스캐피탈,
 [00405092]에스티지시큐리티,
 [00226060]보성설비,
 [00206349]록정개발,
 [00217035]신아스포츠,
 [00224318]뉴라인여신금융,
 [00424945]중소기업제삼차유동화전문유한회사,
 [00428604]알비에이,
 [00424565]체리스톤코리아,
 [00226574]세모화학,
 [00425157]리딩씨앤씨,
 [00427340]폴리코,
 [00427429]산은굿밸류제일차유동화전문유한회사,
 [00420453]이프리즘,
 [00403696]디미디어,
 [00417592]유피텍,
 [00365998]티브이가이드,
 [00412913]스타코리아웹케스팅,
 [00421355]아라정보기술,
 [00426439]코리아컨텐츠네트워크,
 [00427386]티티월드,
 [00167129]흥산건설,
 [00217707]연덕건설,
 [00426518]비추미코리아제일차유동화전문유한회사,
 [00426536]크레디피아제삼십오차유동화전문유한회사,
 [00426545]아하론제삼차유동화전문유한회사,
 [00335951]동원제일차유동화전문,
 [00436588]케이투이,
 [00435349]지영상사,
 [00331450]아주의대벤처메딕스,
 [00341952]엑스퍼트유동화전문유한회사,
 [00342739]마이에셋유동화전문유한회사,
 [00342988]한아름제2차유동화전문유한회사,
 [00436241]에셋외환카드제이차유동화전문유한회사,
 [00436269]에셋외환카드제육차유동화전문유한회사,
 [00436296]타이거유동화전문유한회사,
 [00237491]서한전자,
 [00118099]동원직물,
 [00436685]청유,
 [00437107]서울전산,
 [00436490]씨에스,
 [00436524]선암건설,
 [00435923]아세텔레콤,
 [00437541]우리엘비제칠차유동화전문유한회사,
 [00437569]지오택드레인,
 [00336385]몬덱스코리아,
 [00198253]서광티앤씨,
 [00354062]로직스컴퓨터,
 [00311818]RedTulipInvestments,
 [00452267]아이산업개발,
 [00446141]비코레트,
 [00451365]우림엔지니어링건축사사무소,
 [00263627]백현건설,
 [00413912]우연종합건설,
 [00362618]용성조선,
 [00202404]송원자동차조명,
 [00450773]태산종합건설,
 [00252852]근도물산,
 [00451879]씨에스피산업,
 [00181217]삼흥판지,
 [00375728]인터내셔날쥬피텍,
 [00445823]대륙종합건설,
 [00387167]마시나코아,
 [00256885]부천산업,
 [00452674]바롬테크,
 [00449421]대방종합건설,
 [00209230]영도섬유,
 [00412311]미디어파트너스,
 [00233741]한이해운,
 [00299400]금영,
 [00112518]대준섬유,
 [00416760]두일,
 [00397438]벽송종합건설,
 [00198615]평해건설,
 [00363228]대동제지공업,
 [00415257]동서디엔씨,
 [00369365]케미스,
 [00405126]텔리맨,
 [00415266]과일나라,
 [00361354]넷츠고,
 [00415275]동승건설,
 [00367446]주영크리에이션,
 [00415673]태광엔터프라이즈,
 [00171751]한주종합건설,
 [00416797]유정건설,
 [00193407]세광종합건설,
 [00365943]금양레포츠,
 [00363060]게임벤처,
 [00418892]마이애셋사모M&A펀드B호,
 [00418917]하나로밀레니엄,
 [00417370]메트로에이전시,
 [00427508]국민카드제십차유동화전문유한회사,
 [00367987]시봉전자,
 [00428020]두산스피리츠,
 [00382296]게토코리아,
 [00297332]AmkorTechnology,Inc.,
 [00378929]에이피엠쇼핑몰,
 [00384735]코텍,
 [00303572]아이거넷,
 [00399250]도원닷컴,
 [00434951]맥쿼리장기채권형펀드,
 [00434988]세이리딩스톡혼합형펀드,
 [00434997]세이고배당장기증권저축펀드,
 [00435002]세이고배당주식형펀드,
 [00435136]맥쿼리IMM슈페리어채권형사모펀드,
 [00434331]KTB채권형펀드,
 [00434359]글로벌퍼펙트혼합형펀드,
 [00434377]삼성중소형알짜주식형뮤추얼펀드,
 [00434386]KTB장기증권저축펀드1호,
 [00434438]KTB에이플러스2호혼합형사모펀드,
 [00286877]비비앤씨,
 [00436913]대청산업,
 [00436366]링컨아카데미,
 [00369116]디아이컨설팅,
 [00261577]네띠앙,
 [00434261]크레디피아제삼십팔차유동화전문유한회사,
 [00222204]산내들축산,
 [00436153]거장주택건설,
 [00437967]쓰리디컴넷,
 [00435914]대양식품,
 [00435899]태강건설,
 [00437383]국제전자정밀,
 [00351825]투어토털닷컴,
 [00415008]드림미르,
 [00436968]부광,
 [00436852]도원건설,
 [00436393]현우유통,
 [00261142]엘리온정보기술,
 [00439406]지석공영,
 [00421559]에쓰엠제일차자산유동화전문,
 [00387060]뉴밀레니엄코람제이차유동화전문유한회사,
 [00434067]렉스상사,
 [00450409]엔트,
 [00430283]협성염공,
 [00370875]디비엔지니어링,
 [00230878]삼양텍스,
 [00409867]얄개네트워크,
 [00385044]지트랜코리아,
 [00173245]삼보,
 [00423812]국민카드제구차유동화전문유한회사,
 [00425661]국민카드제십일차유동화전문유한회사,
 [00273907]하나로제4차유동화전문회사,
 [00283533]와이디세이프유동화전문유한회사,
 [00445966]늘푸른마을,
 [00450001]이노크래프트,
 [00449555]강동종합유선방송,
 [00452443]한림하우징,
 [00366836]아이티엠,
 [00444426]코산아이엔티,
 [00261665]미광핸드백,
 [00363945]신정건설,
 [00414832]코이넬,
 [00383161]서울제일차유동화전문유한회사,
 [00163026]이지닷컴,
 [00414610]지에프엠에스,
 [00415947]언아더월드,
 [00304605]로티스,
 [00414957]이파워게이트,
 [00416229]윤진개발,
 [00120243]레이디,
 [00411659]미트마트옥션,
 [00198314]아싸,
 [00413408]웰리치개발,
 [00163965]항도종합금융,
 [00416724]아이텍테크널러지,
 [00218502]중앙제약,
 [00364175]우남산업,
 [00417422]윈로지스뉴톤보레알,
 [00417981]한국지방재정공제회,
 [00307046]창도건설,
 [00237349]부국개발,
 [00414364]유경엔지니어링,
 [00417626]한국레이저영상,
 [00418050]씨에이블,
 [00415567]아토메가,
 [00247984]도레미농산,
 [00371494]다인개발,
 [00358147]호만기업,
 [00150554]갑을개발,
 [00305279]에버그린유동화전문유한회사,
 [00386326]맥트랜스인터내셔날,
 [00100753]거봉,
 [00204703]대산레미콘,
 [00417316]크레딧크리에이터이천이유동화전문유한회사,
 [00207959]신택,
 [00411109]바티오테크,
 [00417477]하우징그룹우신,
 [00414054]통인물류정보통신,
 [00303730]에스지에스컨테크,
 [00362229]광호,
 [00317326]펜다하우스,
 [00418430]프르덴셜어슈어런스컴퍼니리티니드,
 [00434447]KTB장기증권저축펀드,
 [00434526]KTB하이스타혼합형펀드,
 [00433721]한국광학초자,
 [00434207]광평개발,
 [00434562]KTB밸류스타혼합형펀드,
 [00434571]KTB글로벌스타주식형펀드,
 [00434580]KTB프라임4호주식형사모펀드,
 [00434599]KTB베스트바이혼합형펀드,
 [00434605]KTB하이턴펀드,
 [00434614]마이다스A등급채권혼합형펀드,
 [00435145]맥쿼리아이엠엠프라임3혼합형사모펀드,
 [00396448]피이아이코리아사모엠엔에이일호펀드,
 [00430937]아담소프트,
 [00423034]피델리티펀드,
 [00435127]유리크레디트채권혼합형펀드,
 [00434544]KTB프리미엄찬스혼합형펀드,
 [00434553]KTB에이스찬스혼합형펀드,
 [00432050]다린정보,
 [00344843]기보캐피탈제일차유동화전문유한회사,
 [00371908]엘에스에프프로퍼티투유동화전문,
 [00339090]온디지털테크,
 [00337986]캐피탈그룹인터내셔널인코포레이티드,
 [00206136]세림아이텍,
 [00440411]코스유동화전문유한회사,
 [00422309]뉴밀레니엄하나유동화전문유한회사,
 [00439257]동양정보통신M&A,
 [00439284]하이페리온제삼차유동화전문유한회사,
 [00439424]코머스에셋,
 [00435011]경동실업,
 [00428525]에스티엑스제이차유동화전문유한회사,
 [00427128]오일뱅크제삼차유동화전문유한회사,
 [00428677]케이지브이제일차유동화전문유한회사,
 [00436560]인성어패럴,
 [00440697]소프티안,
 [00439734]동양알미늄,
 [00327387]소모페스트,
 [00437611]젤존항공여행사,
 [00321064]바이오엔비텍,
 [00362557]세원반도체,
 [00224105]두원그린피아,
 [00447654]미도핸드백,
 [00453169]대영테크,
 [00371388]아이비젠,
 [00144340]한화포리마,
 [00437204]신케이에스유동화전문유한회사,
 [00443302]프라임유동화전문유한회사,
 [00436463]우영제일차유동화전문유한회사,
 [00452692]한컴리눅스,
 [00441739]두산건설제육유동화전문유한회사,
 [00441669]산은부동산제팔차유동화전문유한회사,
 [00436940]오토피아제칠차유동화전문유한회사,
 [00436959]외환카드제팔차유동화전문유한회사,
 [00427526]삼성신한아하론일차유동화전문유한회사,
 [00264705]현대유동화전문유한회사,
 [00387714]칼제일차유동화전문유한회사,
 [00300946]백두건설,
 [00402086]리엔텍,
 [00452461]대양건설,
 [00100948]건양콘크리트,
 [00365572]맥스미디어,
 [00400486]루넷,
 [00417909]충일아스콘,
 [00153816]태양연와공업,
 [00414586]제동,
 [00187637]농협축산유통,
 [00415035]동서D&S,
 [00235864]에스앤제이,
 [00416043]창영물산,
 [00174280]태화건설,
 [00417352]동방코리아,
 [00238223]영텍스타일,
 [00234740]고려소재개발,
 [00417565]아이앤알코리아기업구조조정전문,
 [00192958]건륭실업,
 [00387459]충주공용버스터미널,
 [00415761]푸른도시개발,
 [00404011]로고스이넷,
 [00168553]대광종합건설,
 [00309804]굿윌씨앤아이,
 [00408600]아라아이디시,
 [00418731]디엠아이디,
 [00363121]웅보개발,
 [00230577]광복산업개발,
 [00295671]리빙티브이,
 [00418759]산은부동산제삼차유동화전문유한회사,
 [00211448]신라,
 [00406170]글로만,
 [00301060]서림개스실린더,
 [00242350]파인에셋홀딩스,
 [00134352]세일,
 [00420569]한일밀라노.존,
 [00422141]첼린저이차유동화전문유한회사,
 [00422178]휴민텍,
 [00419891]템플턴스트래티직이머징마켓츠펀드엘디씨,
 [00419907]신한파이낸스,
 [00310989]코오롱모터스,
 [00420976]큐마트솔루션,
 [00421072]나은미디어,
 [00423706]BystronicLaserAG,
 [00384425]코브코유동화전문유한회사,
 [00350297]칼스버그에이에스,
 [00421124]아이엠씨마케팅,
 [00434632]글로벌채권프리미엄혼합형펀드,
 [00434650]KTB밸류코스닥혼합형펀드,
 [00434669]KTB밸류코리아혼합형사모펀드,
 [00429658]스톰홀딩스,
 [00118831]아이넥스테크놀로지,
 [00205483]세종토건,
 [00434492]부평유선방송,
 [00435622]KTB온누리혼합형펀드,
 [00435631]미래에셋인디펜던스오십혼합형펀드,
 [00435695]KTB드림코스닥혼합형펀드,
 [00434845]유리리버스국채인덱스혼합형펀드,
 [00434854]유리비너스채권형사모펀드,

In [3]:
all = dart_fss.api.filings.get_corp_code()
all[0]

df = pd.DataFrame(all)

df_listed = df[df['stock_code'].notnull()]
df_non_listed = df[df['stock_code'].isnull()]

In [4]:
df_listed

,corp_code,corp_name,corp_eng_name,stock_code,modify_date
1947,00260985,한빛네트,"HanbitNet, Inc.",036720,20170630
1959,00264529,엔플렉스,"Nplex,Inc.",040130,20170630
1960,00358545,동서정보기술,"Dong Seo Information Technology Co., Ltd.",055000,20170630
2702,00231567,애드모바일,None,032600,20170630
3774,00359614,리더컴,"LEADER COMM.Co.,Ltd",056140,20170630
...,...,...,...,...,...
110920,00520887,비상교육,VISANG EDUCATION INC,100220,20240401
110921,00269889,누리플렉스,"NuriFlex Co.,Ltd.",040160,20240401
110922,00633835,HJ중공업,"HJ SHIPBUILDING & CONSTRUCTION CO.,LTD",097230,20240401
110923,01428203,케이씨씨글라스,KCC GLASS Corporation,344820,20240401
110952,00408336,인산가,INSAN Inc.,062580,20240628

In [10]:
df_listed[df_listed['stock_code'] == '005930']

       corp_code corp_name                corp_eng_name stock_code modify_date
102615  00126380      삼성전자  SAMSUNG ELECTRONICS CO,.LTD     005930    20250326

In [5]:
df_non_listed

,corp_code,corp_name,corp_eng_name,stock_code,modify_date
0,00434003,다코,Daco corporation,None,20170630
1,00430964,굿앤엘에스,"Good & LS Co.,Ltd.",None,20170630
2,00388953,크레디피아제이십오차유동화전문회사,Credipia 25th Asset Securitization Specialty L...,None,20170630
3,00179984,연방건설산업,youn bao,None,20170630
4,00420143,브룩스피알아이오토메이션잉크,"BROOKS-PRI Automation, Inc.",None,20170630
...,...,...,...,...,...
111069,01912650,대안일레콤,"daean elecom co., ltd",None,20250422
111070,00912990,유영산업,"YOUYOUNG CO.,LTD.",None,20250422
111071,00100814,포스코이앤씨,"POSCO Eco & Challenge Co., Ltd.",None,20250422
111072,01915046,엘에이치앤디,LH&D INC,None,20250422
111073,01529876,크림,KREAM Corporation,None,20250422

In [7]:
import OpenDartReader


api_key = '79985b0c504cc0bb5fce093fba4fd0be634e04a5'

dart = OpenDartReader(api_key)

dart

In [8]:
dart.list('삼성전자') # 기업이름 혹은,

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126380,삼성전자,005930,Y,주식등의대량보유상황보고서(일반),20250418000638,삼성물산,20250418,
1,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20250411001876,서재홍,20250411,
2,00126380,삼성전자,005930,Y,기업설명회(IR)개최(안내공시),20250408800011,삼성전자,20250408,유
3,00126380,삼성전자,005930,Y,연결재무제표기준영업(잠정)실적(공정공시),20250408800003,삼성전자,20250408,유
4,00126380,삼성전자,005930,Y,최대주주등소유주식변동신고서,20250404801150,삼성전자,20250404,유
...,...,...,...,...,...,...,...,...,...
6143,00126380,삼성전자,005930,Y,채무보증(담보제공포함),20000404000429,삼성전자,20000404,
6144,00126380,삼성전자,005930,Y,최대주주등을위한금전의대여,20000401000031,삼성전자,20000401,
6145,00126380,삼성전자,005930,Y,감사보고서 (1999.12),20000320000124,삼일회계법인,20000320,
6146,00126380,삼성전자,005930,Y,[기재정정]반기보고서 (1999.06),19990824000003,삼성전자,19990824,
6147,00126380,삼성전자,005930,Y,[기재정정]사업보고서 (1998.12),19990626000007,삼성전자,19990626,연

In [12]:
dart.company('00126380')

{'status': '000',
 'message': '정상',
 'corp_code': '00126380',
 'corp_name': '삼성전자(주)',
 'corp_name_eng': 'SAMSUNG ELECTRONICS CO,.LTD',
 'stock_name': '삼성전자',
 'stock_code': '005930',
 'ceo_nm': '전영현',
 'corp_cls': 'Y',
 'jurir_no': '1301110006246',
 'bizr_no': '1248100998',
 'adres': '경기도 수원시 영통구  삼성로 129 (매탄동)',
 'hm_url': 'www.samsung.com/sec',
 'ir_url': '',
 'phn_no': '02-2255-0114',
 'fax_no': '031-200-7538',
 'induty_code': '264',
 'est_dt': '19690113',
 'acc_mt': '12'}

In [13]:
df_listed.to_excel("./stocked_list.xlsx")
df_non_listed.to_excel("./non_stocked_list.xlsx")

In [15]:
len(df)

111074

In [16]:
df.to_excel("./all_list.xlsx")

In [17]:
len(df_non_listed)

107220

In [24]:
corp_code_df = pd.read_excel("./업종코드-표준산업분류 연계표(22.4.19).xlsx")
corp_code_df.shape

(1727, 25)

In [25]:
corp_code_df.head()

,Unnamed: 0,2021년 귀속\n업종코드,대분류,대분류.1,중분류,중분류.1,소분류,소분류.1,세분류,세분류.1,...,중분류.2,중분류.3,소분류.2,소분류.3,세분류.2,세분류.3,세세분류.1,연계.1,메인,Unnamed: 24
0,1.0,11000.0,A,"농업, 임업 및 어업",1.0,농업,11.0,작물 재배업,110.0,곡물 및 기타 식량작물 재배업,...,1.0,농업,11.0,작물 재배업,111.0,곡물 및 기타 식량작물 재배업,곡물 및 기타 식량작물 재배업,1.0,NaN,NaN
1,2.0,11001.0,A,"농업, 임업 및 어업",1.0,농업,11.0,작물 재배업,110.0,"채소, 화훼작물 및 종묘 재배업",...,1.0,농업,11.0,작물 재배업,112.0,"채소, 화훼작물 및 종묘 재배업",채소작물 재배업,1.0,NaN,NaN
2,3.0,11002.0,A,"농업, 임업 및 어업",1.0,농업,11.0,작물 재배업,110.0,"채소, 화훼작물 및 종묘 재배업",...,1.0,농업,11.0,작물 재배업,112.0,"채소, 화훼작물 및 종묘 재배업",화훼작물 재배업,1.0,NaN,NaN
3,4.0,11003.0,A,"농업, 임업 및 어업",1.0,농업,11.0,작물 재배업,110.0,"채소, 화훼작물 및 종묘 재배업",...,1.0,농업,11.0,작물 재배업,112.0,"채소, 화훼작물 및 종묘 재배업",종자 및 묘목 생산업,1.0,NaN,NaN
4,5.0,11004.0,A,"농업, 임업 및 어업",1.0,농업,11.0,작물 재배업,110.0,"과실, 음료용 및 향신용 작물 재배업",...,1.0,농업,11.0,작물 재배업,113.0,"과실, 음료용 및 향신용 작물 재배업",과실작물 재배업,1.0,NaN,NaN

In [30]:
corp_code_df.columns

Index(['Unnamed: 0', '2021년 귀속\n업종코드', '대분류', '대분류.1', '중분류', '중분류.1', '소분류',
       '소분류.1', '세분류', '세분류.1', '세세분류', '연계', '표준산업\n분류', '대분류.2', '대분류.3',
       '중분류.2', '중분류.3', '소분류.2', '소분류.3', '세분류.2', '세분류.3', '세세분류.1', '연계.1',
       '메인', 'Unnamed: 24'],
      dtype='object')

In [34]:
corp_code_df["소분류.2"].unique()

array([ 11.,  12.,  14.,  13.,  15.,  20.,  31.,  32.,  51.,  72.,  61.,
        62.,  71.,  52.,  80., 101., 102., 103., 104., 105., 106., 108.,
       107., 111., 112., 120., 131., 132., 134., 303., 139., 143., 133.,
       144., 141., 142., 151., 152., 161., 162., 163., 171., 172., 179.,
       181., 182., 191., 192., 201., 203., 202., 204., 212., 211., 213.,
       266., 205., 221., 222., 231., 232., 233., 239., 241., 242., 243.,
       251., 259., 291., 292., 252., 285., 263., 262., 281., 283., 282.,
       284., 289., 261., 264., 265., 271., 272., 273., 274., 301., 302.,
       304., 311., 312., 313., 319., 320., 331., 332., 333., 334., 339.,
       759.,  nan, 340., 351., 352., 353., 383., 390., 360., 370., 381.,
       382., 411., 681., 412., 424., 421., 422., 425., 423., 426., 451.,
       452., 453., 477., 461., 462., 463., 464., 465., 466., 467., 468.,
       471., 472., 475., 478., 479., 474., 473., 476., 492., 491., 493.,
       529., 495., 501., 502., 511., 512., 521., 494., 551., 559., 561.,
       562., 581., 592., 611., 612., 631., 620., 582., 639., 591., 601.,
       602., 641., 649., 642., 651., 652., 653., 661., 662., 682., 702.,
       701., 711., 712., 714., 715., 729., 721., 713., 733., 739., 732.,
       716., 731., 764., 752., 761., 763., 762., 751., 753., 742., 743.,
       741., 841., 842., 843., 844., 845., 856., 854., 855., 851., 852.,
       853., 857., 861., 862., 869., 863., 871., 872., 912., 911., 901.,
       902., 969., 951., 953., 952., 961., 941., 942., 949., 970., 990.,
       981., 982.])

In [35]:
corp_code_df["소분류.3"].unique()

array(['작물 재배업', '축산업', '작물재배 및 축산 관련 서비스업', '작물재배 및 축산 복합농업',
       '수렵 및 관련 서비스업', '임업', '어로 어업', '양식어업 및 어업관련 서비스업', '석탄 광업',
       '기타 비금속광물 광업', '철 광업', '비철금속 광업', '토사석 광업', '원유 및 천연가스 채굴업',
       '광업 지원 서비스업', '도축, 육류 가공 및 저장 처리업', '수산물 가공 및 저장 처리업',
       '과실, 채소 가공 및 저장 처리업', '동물성 및 식물성 유지 제조업', '낙농제품 및 식용 빙과류 제조업',
       '곡물 가공품, 전분 및 전분제품 제조업', '동물용 사료 및 조제식품 제조업', '기타 식품 제조업',
       '알코올 음료 제조업', '비알코올 음료 및 얼음 제조업', '담배 제조업', '방적 및 가공사 제조업',
       '직물 직조 및 직물제품 제조업', '섬유제품 염색, 정리 및 마무리 가공업', '자동차 신품 부품 제조업',
       '기타 섬유제품 제조업', '편조의복 제조업', '편조 원단 제조업', '의복 액세서리 제조업', '봉제의복 제조업',
       '모피제품 제조업', '가죽, 가방 및 유사 제품 제조업', '신발 및 신발 부분품 제조업', '제재 및 목재 가공업',
       '나무제품 제조업', '코르크 및 조물 제품 제조업', '펄프, 종이 및 판지 제조업',
       '골판지, 종이 상자 및 종이 용기 제조업', '기타 종이 및 판지 제품 제조업', '인쇄 및 인쇄관련 산업',
       '기록매체 복제업', '코크스 및 연탄 제조업', '석유 정제품 제조업', '기초 화학물질 제조업',
       '비료, 농약 및 살균ㆍ살충제 제조업', '합성고무 및 플라스틱 물질 제조업', '기타 화학제품 제조업',
       '의약품 제조업', '기초 의약 물질 및 생물학적 제제 제조업', '의료용품 및 기타 의약 관련제품 제조업',
       '마그네틱 및 광학 매체 제조업', '화학섬유 제조업', '고무제품 제조업', '플라스틱 제품 제조업',
       '유리 및 유리제품 제조업', '내화, 비내화 요업제품 제조업', '시멘트, 석회, 플라스터 및 그 제품 제조업',
       '기타 비금속 광물제품 제조업', '1차 철강 제조업', '1차 비철금속 제조업', '금속 주조업',
       '구조용 금속제품, 탱크 및 증기발생기 제조업', '기타 금속 가공제품 제조업', '일반 목적용 기계 제조업',
       '특수 목적용 기계 제조업', '무기 및 총포탄 제조업', '가정용 기기 제조업', '컴퓨터 및 주변 장치 제조업',
       '전자 부품 제조업', '전동기, 발전기 및 전기 변환ㆍ공급ㆍ제어 장치 제조업', '절연선 및 케이블 제조업',
       '일차전지 및 축전지 제조업', '전구 및 조명장치 제조업', '기타 전기장비 제조업', '반도체 제조업',
       '통신 및 방송장비 제조업', '영상 및 음향 기기 제조업', '의료용 기기 제조업',
       '측정, 시험, 항해, 제어 및 기타 정밀 기기 제조업; 광학 기기 제외', '사진장비 및 광학 기기 제조업',
       '시계 및 시계 부품 제조업', '자동차용 엔진 및 자동차 제조업', '자동차 차체 및 트레일러 제조업',
       '자동차 재제조 부품 제조업', '선박 및 보트 건조업', '철도장비 제조업', '항공기, 우주선 및 부품 제조업',
       '그 외 기타 운송장비 제조업', '가구 제조업', '귀금속 및 장신용품 제조업', '악기 제조업',
       '운동 및 경기용구 제조업', '인형, 장난감 및 오락용품 제조업', '그 외 기타 제품 제조업',
       '기타 사업 지원 서비스업', '해당사항 없음', '산업용 기계 및 장비 수리업', '전기업',
       '연료용 가스 제조 및 배관공급업', '증기, 냉ㆍ온수 및 공기 조절 공급업', '해체, 선별 및 원료 재생업',
       '환경 정화 및 복원업', '수도업', '하수, 폐수 및 분뇨 처리업', '폐기물 수집, 운반업', '폐기물 처리업',
       '건물 건설업', '부동산 임대 및 공급업', '토목 건설업', '실내건축 및 건축마무리 공사업',
       '기반조성 및 시설물 축조관련 전문공사업', '건물설비 설치 공사업', '시설물 유지관리 공사업',
       '전기 및 통신 공사업', '건설장비 운영업', '자동차 판매업', '자동차 부품 및 내장품 판매업',
       '모터사이클 및 부품 판매업', '연료 소매업', '상품 중개업', '산업용 농ㆍ축산물 및 동ㆍ식물 도매업',
       '음ㆍ식료품 및 담배 도매업', '생활용품 도매업', '기계장비 및 관련 물품 도매업',
       '건축 자재, 철물 및 난방장치 도매업', '기타 전문 도매업', '상품 종합 도매업', '종합 소매업',
       '음ㆍ식료품 및 담배 소매업', '기타 생활용품 소매업', '기타 상품 전문 소매업', '음료 소매업',
       '무점포 소매업', '섬유, 의복, 신발 및 가죽제품 소매업', '가전제품 및 정보 통신장비 소매업',
       '문화, 오락 및 여가 용품 소매업', '육상 여객 운송업', '철도 운송업', '도로 화물 운송업',
       '기타 운송관련 서비스업', '파이프라인 운송업', '해상 운송업', '내륙 수상 및 항만 내 운송업',
       '항공 여객 운송업', '항공 화물 운송업', '보관 및 창고업', '소화물 전문 운송업',
       '일반 및 생활 숙박시설 운영업', '기타 숙박업', '음식점업', '주점 및 비알코올 음료점업',
       '서적, 잡지 및 기타 인쇄물 출판업', '오디오물 출판 및 원판 녹음업', '공영 우편업', '전기 통신업',
       '자료 처리, 호스팅, 포털 및 기타 인터넷 정보 매개 서비스업', '컴퓨터 프로그래밍, 시스템 통합 및 관리업',
       '소프트웨어 개발 및 공급업', '기타 정보 서비스업', '영화, 비디오물, 방송 프로그램 제작 및 배급업',
       '라디오 방송업', '텔레비전 방송업', '확인중', '은행 및 저축기관', '기타 금융업',
       '신탁업 및 집합 투자업', '보험업', '재보험업', '연금 및 공제업', '금융 지원 서비스업',
       '보험 및 연금관련 서비스업', '부동산관련 서비스업', '인문 및 사회과학 연구개발업',
       '자연과학 및 공학 연구개발업', '법무관련 서비스업', '회계 및 세무관련 서비스업', '시장 조사 및 여론 조사업',
       '회사본부 및 경영 컨설팅 서비스업', '기타 과학기술 서비스업', '건축 기술, 엔지니어링 및 관련 기술 서비스업',
       '광고업', '사진 촬영 및 처리업', '그 외 기타 전문, 과학 및 기술 서비스업', '전문 디자인업',
       '기타 전문 서비스업', '수의업', '무형 재산권 임대업', '여행사 및 기타 여행 보조 서비스업',
       '운송장비 임대업', '산업용 기계 및 장비 임대업', '개인 및 가정용품 임대업', '고용 알선 및 인력 공급업',
       '경비, 경호 및 탐정업', '건물ㆍ산업설비 청소 및 방제 서비스업', '조경관리 및 유지 서비스업',
       '사업시설 유지ㆍ관리 서비스업', '기타 사업지원 서비스업', '입법 및 일반 정부 행정', '사회 및 산업정책 행정',
       '외무 및 국방 행정', '사법 및 공공 질서 행정', '사회보장 행정', '기타 교육기관',
       '특수학교, 외국인학교 및 대안학교', '일반 교습학원', '초등 교육기관', '중등 교육기관', '고등 교육기관',
       '교육 지원 서비스업', '병원', '의원', '기타 보건업', '공중 보건 의료업', '거주 복지시설 운영업',
       '비거주 복지시설 운영업', '유원지 및 기타 오락관련 서비스업', '스포츠 서비스업', '창작 및 예술관련 서비스업',
       '도서관, 사적지 및 유사 여가관련 서비스업', '그 외 기타 개인 서비스업', '컴퓨터 및 통신장비 수리업',
       '개인 및 가정용품 수리업', '자동차 및 모터사이클 수리업', '미용, 욕탕 및 유사 서비스업',
       '산업 및 전문가 단체', '노동조합', '기타 협회 및 단체', '가구 내 고용활동', '국제 및 외국기관',
       '자가 소비를 위한 가사 생산 활동', '자가 소비를 위한 가사 서비스 활동'], dtype=object)

In [37]:
induty_code = corp_code_df['소분류.2']

In [38]:
induty_code

0        11.0
1        11.0
2        11.0
3        11.0
4        11.0
        ...
1722    990.0
1723    715.0
1724    715.0
1725    981.0
1726    982.0
Name: 소분류.2, Length: 1727, dtype: float64

In [39]:
induty_name = corp_code_df['소분류.3']

In [40]:
induty_name

0                    작물 재배업
1                    작물 재배업
2                    작물 재배업
3                    작물 재배업
4                    작물 재배업
               ...
1722              국제 및 외국기관
1723     회사본부 및 경영 컨설팅 서비스업
1724     회사본부 및 경영 컨설팅 서비스업
1725     자가 소비를 위한 가사 생산 활동
1726    자가 소비를 위한 가사 서비스 활동
Name: 소분류.3, Length: 1727, dtype: object

In [41]:
induty_df = pd.DataFrame({'induty_code': induty_code, 'induty_name': induty_name})

In [42]:
induty_df.head()

   induty_code induty_name
0         11.0      작물 재배업
1         11.0      작물 재배업
2         11.0      작물 재배업
3         11.0      작물 재배업
4         11.0      작물 재배업

In [46]:
induty_df[induty_df['induty_code'].isnull()]

      induty_code induty_name
623           NaN     해당사항 없음
1244          NaN         확인중
1629          NaN     해당사항 없음

In [47]:
induty_df.dropna(inplace=True)

In [48]:
induty_df[induty_df['induty_code'].isnull()]

Empty DataFrame
Columns: [induty_code, induty_name]
Index: []

In [49]:
induty_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1724 entries, 0 to 1726
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   induty_code  1724 non-null   float64
 1   induty_name  1724 non-null   object
dtypes: float64(1), object(1)
memory usage: 40.4+ KB

In [50]:
induty_df['induty_code'] = induty_df['induty_code'].apply(lambda x: f'{int(x):03d}')

In [51]:
induty_df.head()

  induty_code induty_name
0         011      작물 재배업
1         011      작물 재배업
2         011      작물 재배업
3         011      작물 재배업
4         011      작물 재배업

In [52]:
induty_df.drop_duplicates(inplace=True)

In [54]:
induty_df.shape

(235, 2)

In [55]:
induty_df['induty_code'].unique()

array(['011', '012', '014', '013', '015', '020', '031', '032', '051',
       '072', '061', '062', '071', '052', '080', '101', '102', '103',
       '104', '105', '106', '108', '107', '111', '112', '120', '131',
       '132', '134', '303', '139', '143', '133', '144', '141', '142',
       '151', '152', '161', '162', '163', '171', '172', '179', '181',
       '182', '191', '192', '201', '203', '202', '204', '212', '211',
       '213', '266', '205', '221', '222', '231', '232', '233', '239',
       '241', '242', '243', '251', '259', '291', '292', '252', '285',
       '263', '262', '281', '283', '282', '284', '289', '261', '264',
       '265', '271', '272', '273', '274', '301', '302', '304', '311',
       '312', '313', '319', '320', '331', '332', '333', '334', '339',
       '759', '340', '351', '352', '353', '383', '390', '360', '370',
       '381', '382', '411', '681', '412', '424', '421', '422', '425',
       '423', '426', '451', '452', '453', '477', '461', '462', '463',
       '464', '465', '466', '467', '468', '471', '472', '475', '478',
       '479', '474', '473', '476', '492', '491', '493', '529', '495',
       '501', '502', '511', '512', '521', '494', '551', '559', '561',
       '562', '581', '592', '611', '612', '631', '620', '582', '639',
       '591', '601', '602', '641', '649', '642', '651', '652', '653',
       '661', '662', '682', '702', '701', '711', '712', '714', '715',
       '729', '721', '713', '733', '739', '732', '716', '731', '764',
       '752', '761', '763', '762', '751', '753', '742', '743', '741',
       '841', '842', '843', '844', '845', '856', '854', '855', '851',
       '852', '853', '857', '861', '862', '869', '863', '871', '872',
       '912', '911', '901', '902', '969', '951', '953', '952', '961',
       '941', '942', '949', '970', '990', '981', '982'], dtype=object)

In [56]:
induty_df[induty_df['induty_code'] == '264']

    induty_code    induty_name
528         264  통신 및 방송장비 제조업

In [57]:
df.head()

,corp_code,corp_name,corp_eng_name,stock_code,modify_date
0,00434003,다코,Daco corporation,None,20170630
1,00430964,굿앤엘에스,"Good & LS Co.,Ltd.",None,20170630
2,00388953,크레디피아제이십오차유동화전문회사,Credipia 25th Asset Securitization Specialty L...,None,20170630
3,00179984,연방건설산업,youn bao,None,20170630
4,00420143,브룩스피알아이오토메이션잉크,"BROOKS-PRI Automation, Inc.",None,20170630

In [62]:
samsung  = dart.company('삼성전자') # 기업이름 혹은,

In [64]:
samsung['induty_code']

'264'

In [65]:
df_listed['induty_code'] = df_listed['corp_code'].apply(lambda x: dart.company(x)['induty_code'])

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_35244\994305385.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_listed['induty_code'] = df_listed['corp_code'].apply(lambda x: dart.company(x)['induty_code'])

In [66]:
df_listed.head()

,corp_code,corp_name,corp_eng_name,stock_code,modify_date,induty_code
1947,00260985,한빛네트,"HanbitNet, Inc.",036720,20170630,58221
1959,00264529,엔플렉스,"Nplex,Inc.",040130,20170630,58221
1960,00358545,동서정보기술,"Dong Seo Information Technology Co., Ltd.",055000,20170630,58221
2702,00231567,애드모바일,None,032600,20170630,58221
3774,00359614,리더컴,"LEADER COMM.Co.,Ltd",056140,20170630,26410

In [67]:
df_listed[df_listed["corp_name"] == "삼성전자"]

,corp_code,corp_name,corp_eng_name,stock_code,modify_date,induty_code
102615,00126380,삼성전자,"SAMSUNG ELECTRONICS CO,.LTD",005930,20250326,264

In [68]:
df_listed.to_excel("./stocked_list_with_induty_code.xlsx")

In [70]:
corp_code_df.columns

Index(['Unnamed: 0', '2021년 귀속\n업종코드', '대분류', '대분류.1', '중분류', '중분류.1', '소분류',
       '소분류.1', '세분류', '세분류.1', '세세분류', '연계', '표준산업\n분류', '대분류.2', '대분류.3',
       '중분류.2', '중분류.3', '소분류.2', '소분류.3', '세분류.2', '세분류.3', '세세분류.1', '연계.1',
       '메인', 'Unnamed: 24'],
      dtype='object')

In [77]:
corp_code_df["소분류.3"].unique()

array(['작물 재배업', '축산업', '작물재배 및 축산 관련 서비스업', '작물재배 및 축산 복합농업',
       '수렵 및 관련 서비스업', '임업', '어로 어업', '양식어업 및 어업관련 서비스업', '석탄 광업',
       '기타 비금속광물 광업', '철 광업', '비철금속 광업', '토사석 광업', '원유 및 천연가스 채굴업',
       '광업 지원 서비스업', '도축, 육류 가공 및 저장 처리업', '수산물 가공 및 저장 처리업',
       '과실, 채소 가공 및 저장 처리업', '동물성 및 식물성 유지 제조업', '낙농제품 및 식용 빙과류 제조업',
       '곡물 가공품, 전분 및 전분제품 제조업', '동물용 사료 및 조제식품 제조업', '기타 식품 제조업',
       '알코올 음료 제조업', '비알코올 음료 및 얼음 제조업', '담배 제조업', '방적 및 가공사 제조업',
       '직물 직조 및 직물제품 제조업', '섬유제품 염색, 정리 및 마무리 가공업', '자동차 신품 부품 제조업',
       '기타 섬유제품 제조업', '편조의복 제조업', '편조 원단 제조업', '의복 액세서리 제조업', '봉제의복 제조업',
       '모피제품 제조업', '가죽, 가방 및 유사 제품 제조업', '신발 및 신발 부분품 제조업', '제재 및 목재 가공업',
       '나무제품 제조업', '코르크 및 조물 제품 제조업', '펄프, 종이 및 판지 제조업',
       '골판지, 종이 상자 및 종이 용기 제조업', '기타 종이 및 판지 제품 제조업', '인쇄 및 인쇄관련 산업',
       '기록매체 복제업', '코크스 및 연탄 제조업', '석유 정제품 제조업', '기초 화학물질 제조업',
       '비료, 농약 및 살균ㆍ살충제 제조업', '합성고무 및 플라스틱 물질 제조업', '기타 화학제품 제조업',
       '의약품 제조업', '기초 의약 물질 및 생물학적 제제 제조업', '의료용품 및 기타 의약 관련제품 제조업',
       '마그네틱 및 광학 매체 제조업', '화학섬유 제조업', '고무제품 제조업', '플라스틱 제품 제조업',
       '유리 및 유리제품 제조업', '내화, 비내화 요업제품 제조업', '시멘트, 석회, 플라스터 및 그 제품 제조업',
       '기타 비금속 광물제품 제조업', '1차 철강 제조업', '1차 비철금속 제조업', '금속 주조업',
       '구조용 금속제품, 탱크 및 증기발생기 제조업', '기타 금속 가공제품 제조업', '일반 목적용 기계 제조업',
       '특수 목적용 기계 제조업', '무기 및 총포탄 제조업', '가정용 기기 제조업', '컴퓨터 및 주변 장치 제조업',
       '전자 부품 제조업', '전동기, 발전기 및 전기 변환ㆍ공급ㆍ제어 장치 제조업', '절연선 및 케이블 제조업',
       '일차전지 및 축전지 제조업', '전구 및 조명장치 제조업', '기타 전기장비 제조업', '반도체 제조업',
       '통신 및 방송장비 제조업', '영상 및 음향 기기 제조업', '의료용 기기 제조업',
       '측정, 시험, 항해, 제어 및 기타 정밀 기기 제조업; 광학 기기 제외', '사진장비 및 광학 기기 제조업',
       '시계 및 시계 부품 제조업', '자동차용 엔진 및 자동차 제조업', '자동차 차체 및 트레일러 제조업',
       '자동차 재제조 부품 제조업', '선박 및 보트 건조업', '철도장비 제조업', '항공기, 우주선 및 부품 제조업',
       '그 외 기타 운송장비 제조업', '가구 제조업', '귀금속 및 장신용품 제조업', '악기 제조업',
       '운동 및 경기용구 제조업', '인형, 장난감 및 오락용품 제조업', '그 외 기타 제품 제조업',
       '기타 사업 지원 서비스업', '해당사항 없음', '산업용 기계 및 장비 수리업', '전기업',
       '연료용 가스 제조 및 배관공급업', '증기, 냉ㆍ온수 및 공기 조절 공급업', '해체, 선별 및 원료 재생업',
       '환경 정화 및 복원업', '수도업', '하수, 폐수 및 분뇨 처리업', '폐기물 수집, 운반업', '폐기물 처리업',
       '건물 건설업', '부동산 임대 및 공급업', '토목 건설업', '실내건축 및 건축마무리 공사업',
       '기반조성 및 시설물 축조관련 전문공사업', '건물설비 설치 공사업', '시설물 유지관리 공사업',
       '전기 및 통신 공사업', '건설장비 운영업', '자동차 판매업', '자동차 부품 및 내장품 판매업',
       '모터사이클 및 부품 판매업', '연료 소매업', '상품 중개업', '산업용 농ㆍ축산물 및 동ㆍ식물 도매업',
       '음ㆍ식료품 및 담배 도매업', '생활용품 도매업', '기계장비 및 관련 물품 도매업',
       '건축 자재, 철물 및 난방장치 도매업', '기타 전문 도매업', '상품 종합 도매업', '종합 소매업',
       '음ㆍ식료품 및 담배 소매업', '기타 생활용품 소매업', '기타 상품 전문 소매업', '음료 소매업',
       '무점포 소매업', '섬유, 의복, 신발 및 가죽제품 소매업', '가전제품 및 정보 통신장비 소매업',
       '문화, 오락 및 여가 용품 소매업', '육상 여객 운송업', '철도 운송업', '도로 화물 운송업',
       '기타 운송관련 서비스업', '파이프라인 운송업', '해상 운송업', '내륙 수상 및 항만 내 운송업',
       '항공 여객 운송업', '항공 화물 운송업', '보관 및 창고업', '소화물 전문 운송업',
       '일반 및 생활 숙박시설 운영업', '기타 숙박업', '음식점업', '주점 및 비알코올 음료점업',
       '서적, 잡지 및 기타 인쇄물 출판업', '오디오물 출판 및 원판 녹음업', '공영 우편업', '전기 통신업',
       '자료 처리, 호스팅, 포털 및 기타 인터넷 정보 매개 서비스업', '컴퓨터 프로그래밍, 시스템 통합 및 관리업',
       '소프트웨어 개발 및 공급업', '기타 정보 서비스업', '영화, 비디오물, 방송 프로그램 제작 및 배급업',
       '라디오 방송업', '텔레비전 방송업', '확인중', '은행 및 저축기관', '기타 금융업',
       '신탁업 및 집합 투자업', '보험업', '재보험업', '연금 및 공제업', '금융 지원 서비스업',
       '보험 및 연금관련 서비스업', '부동산관련 서비스업', '인문 및 사회과학 연구개발업',
       '자연과학 및 공학 연구개발업', '법무관련 서비스업', '회계 및 세무관련 서비스업', '시장 조사 및 여론 조사업',
       '회사본부 및 경영 컨설팅 서비스업', '기타 과학기술 서비스업', '건축 기술, 엔지니어링 및 관련 기술 서비스업',
       '광고업', '사진 촬영 및 처리업', '그 외 기타 전문, 과학 및 기술 서비스업', '전문 디자인업',
       '기타 전문 서비스업', '수의업', '무형 재산권 임대업', '여행사 및 기타 여행 보조 서비스업',
       '운송장비 임대업', '산업용 기계 및 장비 임대업', '개인 및 가정용품 임대업', '고용 알선 및 인력 공급업',
       '경비, 경호 및 탐정업', '건물ㆍ산업설비 청소 및 방제 서비스업', '조경관리 및 유지 서비스업',
       '사업시설 유지ㆍ관리 서비스업', '기타 사업지원 서비스업', '입법 및 일반 정부 행정', '사회 및 산업정책 행정',
       '외무 및 국방 행정', '사법 및 공공 질서 행정', '사회보장 행정', '기타 교육기관',
       '특수학교, 외국인학교 및 대안학교', '일반 교습학원', '초등 교육기관', '중등 교육기관', '고등 교육기관',
       '교육 지원 서비스업', '병원', '의원', '기타 보건업', '공중 보건 의료업', '거주 복지시설 운영업',
       '비거주 복지시설 운영업', '유원지 및 기타 오락관련 서비스업', '스포츠 서비스업', '창작 및 예술관련 서비스업',
       '도서관, 사적지 및 유사 여가관련 서비스업', '그 외 기타 개인 서비스업', '컴퓨터 및 통신장비 수리업',
       '개인 및 가정용품 수리업', '자동차 및 모터사이클 수리업', '미용, 욕탕 및 유사 서비스업',
       '산업 및 전문가 단체', '노동조합', '기타 협회 및 단체', '가구 내 고용활동', '국제 및 외국기관',
       '자가 소비를 위한 가사 생산 활동', '자가 소비를 위한 가사 서비스 활동'], dtype=object)

In [78]:
corp_code_df[corp_code_df["소분류.3"] == "통신 및 방송장비 제조업"]

,Unnamed: 0,2021년 귀속\n업종코드,대분류,대분류.1,중분류,중분류.1,소분류,소분류.1,세분류,세분류.1,...,중분류.2,중분류.3,소분류.2,소분류.3,세분류.2,세분류.3,세세분류.1,연계.1,메인,Unnamed: 24
528,508.0,322002.0,C,제조업,32.0,"전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",322.0,통신 및 방송장비 제조업,3220.0,유선 통신장비 제조업,...,26.0,"전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",264.0,통신 및 방송장비 제조업,2641.0,유선 통신장비 제조업,유선 통신장비 제조업,1.0,NaN,NaN
529,509.0,322003.0,C,제조업,32.0,"전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",322.0,통신 및 방송장비 제조업,3220.0,방송 및 무선 통신장비 제조업,...,26.0,"전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",264.0,통신 및 방송장비 제조업,2642.0,방송 및 무선 통신장비 제조업,방송장비 제조업,1.0,NaN,NaN
530,510.0,322004.0,C,제조업,32.0,"전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",322.0,통신 및 방송장비 제조업,3220.0,방송 및 무선 통신장비 제조업,...,26.0,"전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",264.0,통신 및 방송장비 제조업,2642.0,방송 및 무선 통신장비 제조업,이동 전화기 제조업,1.0,NaN,NaN
531,511.0,322005.0,C,제조업,32.0,"전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",322.0,통신 및 방송장비 제조업,3220.0,방송 및 무선 통신장비 제조업,...,26.0,"전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",264.0,통신 및 방송장비 제조업,2642.0,방송 및 무선 통신장비 제조업,기타 무선 통신장비 제조업,1.0,NaN,NaN

In [79]:
corp_code_df = pd.read_excel("./업종코드-표준산업분류 연계표(22.4.19).xlsx")
corp_code_df.columns

Index(['Unnamed: 0', '2021년 귀속\n업종코드', '대분류', '대분류.1', '중분류', '중분류.1', '소분류',
       '소분류.1', '세분류', '세분류.1', '세세분류', '연계', '표준산업분류', '대분류.2', '대분류.3',
       '중분류.2', '중분류.3', '소분류.2', '소분류.3', '세분류.2', '세분류.3', '세세분류.1', '연계.1',
       '메인', 'Unnamed: 24'],
      dtype='object')

In [80]:
corp_code_df[corp_code_df["표준산업분류"] == "264"]

Empty DataFrame
Columns: [Unnamed: 0, 2021년 귀속
업종코드, 대분류, 대분류.1, 중분류, 중분류.1, 소분류, 소분류.1, 세분류, 세분류.1, 세세분류, 연계, 표준산업분류, 대분류.2, 대분류.3, 중분류.2, 중분류.3, 소분류.2, 소분류.3, 세분류.2, 세분류.3, 세세분류.1, 연계.1, 메인, Unnamed: 24]
Index: []

[0 rows x 25 columns]

In [81]:
df_with_induty_name = pd.read_csv("Revised_Industry_Names_Mapping.csv")

In [84]:
df_with_induty_name.head()

,Unnamed: 0,corp_code,corp_name,corp_eng_name,stock_code,modify_date,induty_code,induty_name
0,1947,260985,한빛네트,"HanbitNet, Inc.",36720,20170630,58221,Unknown
1,1959,264529,엔플렉스,"Nplex,Inc.",40130,20170630,58221,Unknown
2,1960,358545,동서정보기술,"Dong Seo Information Technology Co., Ltd.",55000,20170630,58221,Unknown
3,2702,231567,애드모바일,NaN,32600,20170630,58221,Unknown
4,3774,359614,리더컴,"LEADER COMM.Co.,Ltd",56140,20170630,26410,비금속 광물제품 제조업

In [85]:
df_with_induty_name[df_with_induty_name["corp_name"] == "삼성전자"]

,Unnamed: 0,corp_code,corp_name,corp_eng_name,stock_code,modify_date,induty_code,induty_name
2724,102615,126380,삼성전자,"SAMSUNG ELECTRONICS CO,.LTD",5930,20250326,264,비금속 광물제품 제조업