In [1]:
import pandas as pd

In [2]:
sotcked_list_with_induty_code = pd.read_excel("./stocked_list_with_induty_code.xlsx")
sotcked_list_with_induty_code.head()

,Unnamed: 0,corp_code,corp_name,corp_eng_name,stock_code,modify_date,induty_code
0,1947,260985,한빛네트,"HanbitNet, Inc.",36720,20170630,58221
1,1959,264529,엔플렉스,"Nplex,Inc.",40130,20170630,58221
2,1960,358545,동서정보기술,"Dong Seo Information Technology Co., Ltd.",55000,20170630,58221
3,2702,231567,애드모바일,NaN,32600,20170630,58221
4,3774,359614,리더컴,"LEADER COMM.Co.,Ltd",56140,20170630,26410

In [3]:
sotcked_list_with_induty_code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3854 entries, 0 to 3853
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     3854 non-null   int64
 1   corp_code      3854 non-null   int64
 2   corp_name      3854 non-null   object
 3   corp_eng_name  3851 non-null   object
 4   stock_code     3854 non-null   int64
 5   modify_date    3854 non-null   int64
 6   induty_code    3854 non-null   int64
dtypes: int64(5), object(2)
memory usage: 210.9+ KB

In [4]:
industries_df = pd.read_excel("한국표준산업분류_수정본.xlsx")
industries_df.head()

,Unnamed: 0,코드,항목명,중분류 코드,중분류 항목명,소분류 코드,소분류 항목명,세분류 코드,세분류 항목명,세세분류 코드,세세분류 항목명
0,0,A,"농업, 임업 및 어업(01~03)",1.0,농업,11.0,작물 재배업,111.0,곡물 및 기타 식량작물 재배업,1110.0,곡물 및 기타 식량작물 재배업
1,1,NaN,NaN,NaN,NaN,NaN,NaN,112.0,"채소, 화훼작물 및 종묘 재배업",1121.0,채소작물 재배업
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1122.0,화훼작물 재배업
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1123.0,종자 및 묘목 생산업
4,4,NaN,NaN,NaN,NaN,NaN,NaN,113.0,"과실, 음료용 및 향신용 작물 재배업",1131.0,과실작물 재배업

In [5]:
industries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1197 non-null   int64
 1   코드          21 non-null     object
 2   항목명         21 non-null     object
 3   중분류 코드      77 non-null     float64
 4   중분류 항목명     77 non-null     object
 5   소분류 코드      232 non-null    float64
 6   소분류 항목명     232 non-null    object
 7   세분류 코드      495 non-null    float64
 8   세분류 항목명     495 non-null    object
 9   세세분류 코드     1196 non-null   float64
 10  세세분류 항목명    1196 non-null   object
dtypes: float64(4), int64(1), object(6)
memory usage: 103.0+ KB

In [6]:
# null이 아닌 값에 대해 패딩을 추가하는 함수 정의
def add_padding(value, target_length, pad_char='0'):
    if pd.isna(value):
        return value
    # 소수점 제거하고 정수 부분만 사용
    int_value = str(int(float(value)))
    # 왼쪽에 패딩 추가
    return pad_char * (target_length - len(int_value)) + int_value

# 각 분류 코드 컬럼에 패딩 적용
industries_df['중분류 코드'] = industries_df['중분류 코드'].apply(lambda x: add_padding(x, 2) if pd.notna(x) else x)
industries_df['소분류 코드'] = industries_df['소분류 코드'].apply(lambda x: add_padding(x, 3) if pd.notna(x) else x)
industries_df['세분류 코드'] = industries_df['세분류 코드'].apply(lambda x: add_padding(x, 4) if pd.notna(x) else x)
industries_df['세세분류 코드'] = industries_df['세세분류 코드'].apply(lambda x: add_padding(x, 5) if pd.notna(x) else x)

In [7]:
industries_df.head()

,Unnamed: 0,코드,항목명,중분류 코드,중분류 항목명,소분류 코드,소분류 항목명,세분류 코드,세분류 항목명,세세분류 코드,세세분류 항목명
0,0,A,"농업, 임업 및 어업(01~03)",01,농업,011,작물 재배업,0111,곡물 및 기타 식량작물 재배업,01110,곡물 및 기타 식량작물 재배업
1,1,NaN,NaN,NaN,NaN,NaN,NaN,0112,"채소, 화훼작물 및 종묘 재배업",01121,채소작물 재배업
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01122,화훼작물 재배업
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01123,종자 및 묘목 생산업
4,4,NaN,NaN,NaN,NaN,NaN,NaN,0113,"과실, 음료용 및 향신용 작물 재배업",01131,과실작물 재배업

In [8]:
industries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1197 non-null   int64
 1   코드          21 non-null     object
 2   항목명         21 non-null     object
 3   중분류 코드      77 non-null     object
 4   중분류 항목명     77 non-null     object
 5   소분류 코드      232 non-null    object
 6   소분류 항목명     232 non-null    object
 7   세분류 코드      495 non-null    object
 8   세분류 항목명     495 non-null    object
 9   세세분류 코드     1196 non-null   object
 10  세세분류 항목명    1196 non-null   object
dtypes: int64(1), object(10)
memory usage: 103.0+ KB

In [10]:
def map_industry_code_to_name(stocked_list_with_induty_code, industries_df):
    # 결과를 저장할 리스트 초기화
    industry_names = []
    
    # 각 행에 대해 처리
    for induty_code in stocked_list_with_induty_code['induty_code']:
        # 코드가 없는 경우 처리
        if pd.isna(induty_code):
            industry_names.append('기타')
            continue
        
        # 코드를 문자열로 변환
        if not isinstance(induty_code, str):
            # 소수점 제거 (예: 1.0 -> '1')
            if isinstance(induty_code, float):
                induty_code = str(int(induty_code))
            else:
                induty_code = str(induty_code)
        
        code_length = len(induty_code)
        
        # 코드 길이에 따라 분기 처리
        if code_length == 2:
            # 중분류 코드에서 찾기
            match = industries_df[industries_df['중분류 코드'].astype(str) == induty_code]
            if not match.empty:
                industry_names.append(match.iloc[0]['중분류 항목명'])
            else:
                industry_names.append('기타')
                
        elif code_length == 3:
            # 소분류 코드에서 찾기
            match = industries_df[industries_df['소분류 코드'].astype(str) == induty_code]
            if not match.empty:
                industry_names.append(match.iloc[0]['소분류 항목명'])
            else:
                industry_names.append('기타')
                
        elif code_length == 4:
            # 세분류 코드에서 찾기
            match = industries_df[industries_df['세분류 코드'].astype(str) == induty_code]
            if not match.empty:
                industry_names.append(match.iloc[0]['세분류 항목명'])
            else:
                industry_names.append('기타')
                
        elif code_length == 5:
            # 세세분류 코드에서 찾기
            match = industries_df[industries_df['세세분류 코드'].astype(str) == induty_code]
            if not match.empty:
                industry_names.append(match.iloc[0]['세세분류 항목명'])
            else:
                industry_names.append('기타')
                
        else:
            # 코드 길이가 2~5 범위를 벗어나면 '기타'로 설정
            industry_names.append('기타')
    
    # 결과 리스트를 데이터프레임에 새 컬럼으로 추가
    stocked_list_with_induty_code['induty_name'] = industry_names
    
    return stocked_list_with_induty_code

# 함수 사용
stocked_list_with_induty_code = map_industry_code_to_name(sotcked_list_with_induty_code, industries_df)

In [11]:
stocked_list_with_induty_code.head()

,Unnamed: 0,corp_code,corp_name,corp_eng_name,stock_code,modify_date,induty_code,induty_name
0,1947,260985,한빛네트,"HanbitNet, Inc.",36720,20170630,58221,시스템 소프트웨어 개발 및 공급업
1,1959,264529,엔플렉스,"Nplex,Inc.",40130,20170630,58221,시스템 소프트웨어 개발 및 공급업
2,1960,358545,동서정보기술,"Dong Seo Information Technology Co., Ltd.",55000,20170630,58221,시스템 소프트웨어 개발 및 공급업
3,2702,231567,애드모바일,NaN,32600,20170630,58221,시스템 소프트웨어 개발 및 공급업
4,3774,359614,리더컴,"LEADER COMM.Co.,Ltd",56140,20170630,26410,유선 통신장비 제조업

In [12]:
stocked_list_with_induty_code["induty_name"].unique()

array(['시스템 소프트웨어 개발 및 공급업', '유선 통신장비 제조업', '기타 무선 통신장비 제조업',
       '그 외 기타 기계 및 장비 도매업', '가전제품 및 부품 도매업', '경영 컨설팅업',
       '인쇄회로기판 및 전자부품 실장기판 제조업', '여자용 겉옷 제조업', '감광 재료 및 관련 화학제품 제조업',
       '전문직별 공사업', '신용조합', '기타 금융 투자업', '백화점', '데이터베이스 및 온라인 정보 제공업',
       '방송 및 무선 통신장비 제조업', '컴퓨터 및 주변장치, 소프트웨어 도매업', '솜 및 실 염색 가공업',
       '전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업', '일반 목적용 기계 제조업', '남자용 겉옷 제조업',
       '다이오드, 트랜지스터 및 유사 반도체 소자 제조업', '기타 전문 도매업', '기타 절연선 및 케이블 제조업',
       '기타 통신 판매업', '기관 구내식당업', '그 외 기타 여신 금융업', '방사선 장치 제조업',
       '영화, 비디오물 및 방송 프로그램 제작업', '플라스틱 합성피혁 제조업', '음료 제조업',
       '금속 열처리, 도금 및 기타 금속 가공업', '일반 영화 및 비디오물 제작업', '특수 목적용 기계 제조업',
       '반도체 제조용 기계 제조업', '방송 프로그램 제작업', '비주거용 건물 임대업',
       '컴퓨터 시스템 통합 자문 및 구축 서비스업', '기타 전자 부품 제조업', '기타 방적업', '인테리어 디자인업',
       '상품 종합 도매업', '신탁업 및 집합 투자업', '안경, 사진장비 및 광학용품 도매업',
       '전기식 진단 및 요법 기기 제조업', '트레일러 및 세미 트레일러 제조업', '기타 봉제의복 제조업',
       '속도계 및 적산계기 제조업', '사업시설 유지ㆍ관리 서비스업', '상품 중개업', '전자집적회로 제조업',
       '전동기, 발전기 및 전기 변환장치 제조업', '어망 및 기타 끈 가공품 제조업', '유선 통신업',
       '기타 금속 가공제품 제조업', '구조용 금속제품 제조업', '외항 화물 운송업', '여행사업',
       '그 외 기타 분류 안된 금융업', '상호 저축은행 및 기타 저축기관', '환경설비 건설업', '날붙이 제조업',
       '통신 판매업', '부동산 임대업', '기타 기계 및 장비 도매업', '속옷 및 잠옷 제조업', '도로 건설업',
       '교과서 및 학습 서적 출판업', '기타 정보 기술 및 컴퓨터 운영 관련 서비스업',
       '회사 본부 및 경영 컨설팅 서비스업', '절연 코드세트 및 기타 도체 제조업', '기타 부동산 개발 및 공급업',
       '컴퓨터 및 주변 장치 제조업', '무선 및 위성 통신업', '공연 기획업', '기억 장치 제조업',
       '기계장비 조립용 플라스틱제품 제조업', '주거용 건물 건설업', '기타 가정용 전기 기기 제조업', '지주회사',
       '알루미늄 압연, 압출 및 연신제품 제조업', '액정 표시장치 제조업', '컴퓨터 제조업',
       '디스플레이 제조용 기계 제조업', '기타 고무제품 제조업', '금속 주조 및 기타 야금용 기계 제조업',
       '축전지 제조업', '매니저업', '오락 및 스포츠용 보트 건조업', '핸드백 및 지갑 제조업',
       '기타 플라스틱 제품 제조업', '그 외 기타 의료용 기기 제조업', '의료, 정밀, 광학 기기 및 시계 제조업',
       '게임 소프트웨어 개발 및 공급업', '손해보험업', '음악 및 기타 오디오물 출판업',
       '배전반 및 전기 자동제어반 제조업', '기타 운송장비 임대업', '기타 1차 철강 제조업', '자동차 신품 판매업',
       '일반 철물 제조업', '온라인 교육학원', '기타 금융 지원 서비스업', '전자기 측정, 시험 및 분석 기구 제조업',
       '자동차 및 트레일러 제조업', '섬유, 의복, 신발 및 가죽제품 중개업', '냉간 압연 및 압출 제품 제조업',
       '모직물 직조업', '응용 소프트웨어 개발 및 공급업', '그 외 기타 금융 지원 서비스업',
       '기타 엔지니어링 서비스업', '그 외 기타 화학제품 제조업', '금속 단조제품 제조업', '기타 화학제품 제조업',
       '금융업', '그 외 기타 금융업', '봉제의복 제조업', '산업 처리공정 제어장비 제조업',
       '합성수지 및 기타 플라스틱 물질 제조업', '주거용 건물 개발 및 공급업', '일반 교과학원',
       '플라스틱 선, 봉, 관 및 호스 제조업', '석유화학계 기초 화학 물질 제조업', '서적 출판업',
       '가방 및 기타 보호용 케이스 제조업', '금융 및 보험관련 서비스업', '면 방적업', '반도체 제조업',
       '기타 금융업', '강 주물 주조업', '증권 중개업', '기록매체 복제업', '사무용 기계 및 장비 제조업',
       '비동력식 수공구 제조업', '전자 응용 절삭기계 제조업', '경비 및 경호 서비스업', '기타 부동산 임대업',
       '화학섬유직물 직조업', '시멘트 제조업', '모피 및 가죽 제조업', '포장용 유리용기 제조업',
       '기타 구조용 금속제품 제조업', '신용카드 및 할부 금융업', '전기 경보 및 신호장치 제조업',
       '부직포 및 펠트 제조업', '기타 기술 시험, 검사 및 분석업', '전구 및 램프 제조업', '기타',
       '공기 조화장치 제조업', '국내은행', '기기용 자동 측정 및 제어장치 제조업',
       '영화, 비디오물 및 방송 프로그램 배급업', '특수직물 및 기타 직물 직조업', '레미콘 제조업',
       '교육관련 자문 및 평가업', '애니메이션 영화 및 비디오물 제작업', '화학섬유 방적업',
       '남녀용 겉옷 및 셔츠 도매업', '통신 및 방송장비 제조업', '포장용 플라스틱 성형용기 제조업',
       '금융 지원 서비스업', '1차 금속제품 도매업', '운송장비 임대업', '방적 및 가공사 제조업', '유선 방송업',
       '전자 부품 제조업', '일반용 도료 및 관련제품 제조업', '해상 운송업', '실내건축 및 건축마무리 공사업',
       '영화, 비디오물, 방송 프로그램 제작 및 배급업', '펄프, 종이 및 판지 제조업', '아파트 건설업',
       '도매 및 상품 중개업', '알루미늄 제련, 정련 및 합금 제조업',
       '석탄화학계 화합물 및 기타 기초 유기화학 물질 제조업', '도축업', '가공 공작기계 제조업',
       '부동산 임대 및 공급업', '컴퓨터 학원', '부동산업', '철강관 제조업',
       '구조용 금속 판제품 및 공작물 제조업', '일차전지 제조업', '그 외 기타 분류 안된 사업 지원 서비스업',
       '전자 저항기 제조업', '그 외 기타 금속 가공제품 제조업', '화장품 제조업', '소프트웨어 개발 및 공급업',
       '석유 정제품 제조업', '1차 플라스틱제품 제조업', '기타 종이 및 판지 제품 제조업', '기초 화학물질 제조업',
       '영상게임기 제조업', '포털 및 기타 인터넷 정보 매개 서비스업', '기어 및 동력전달장치 제조업',
       '치약, 비누 및 기타 세제 제조업', '합성섬유 제조업', '탭, 밸브 및 유사 장치 제조업', '합금철 제조업',
       '텔레비전 방송업', '이동 전화기 제조업', '전기 및 통신 공사업', '일반 교습학원', '동물용 의약품 제조업',
       '오프셋 인쇄업', '그 외 기타 전기장비 제조업', '의료용 기기 제조업', '1차 비철금속 제조업',
       '일반용 전기 조명장치 제조업', '화장품, 비누 및 방향제 소매업', '선철 주물 주조업', '방송장비 제조업',
       '일반 화물 자동차 운송업', '기타 목재 가구 제조업', '자연과학 및 공학 연구개발업', '사료 도매업',
       '편조의복 제조업', '판유리 및 판유리 가공품 제조업', '의학 및 약학 연구개발업',
       '전기용 기계ㆍ장비 및 관련 기자재 도매업', '핵반응기 및 증기보일러 제조업', '침구 및 관련제품 제조업',
       '선박 구성 부분품 제조업', '자동차 신품 부품 제조업', '농업 및 임업용 기계 제조업', '전자 축전기 제조업',
       '지상파 방송업', '전구 및 조명장치 제조업', '직물 직조 및 직물제품 제조업', '스포츠 서비스업',
       '선박 및 수상 부유 구조물 건조업', '토목 건설업', '종합 소매업', '강관 가공품 및 관 연결구류 제조업',
       '그 외 기타 전자 부품 제조업', '골판지 및 골판지 가공제품 제조업', '윤활유 및 그리스 제조업', '생명보험업',
       '사진장비 및 광학 기기 제조업', '기타 비금속 광물제품 제조업', '산업용 로봇 제조업',
       '그 외 기타 특수 목적용 기계 제조업', '기타 주변 기기 제조업', '기타 사업 지원 서비스업',
       '자동차 신품 부품 및 내장품 판매업', '기타 측정, 시험, 항해, 제어 및 정밀 기기 제조업',
       '컴퓨터 프로그래밍, 시스템 통합 및 관리업', '자료 처리, 호스팅, 포털 및 기타 인터넷 정보 매개 서비스업',
       '플라스틱 창호 제조업', '연료용 가스 제조 및 배관공급업', '직물포대 제조업',
       '플라스틱 포대, 봉투 및 유사제품 제조업', '기타 전기장비 제조업', '식품 위생용 종이 상자 및 용기 제조업',
       '제철, 제강 및 합금철 제조업', '호스팅 및 관련 서비스업', '의약품 제조업',
       '기초 의약 물질 및 생물학적 제제 제조업', '비료 및 질소 화합물 제조업', '일반 제재업',
       '수동식 식품 가공 기기 및 금속 주방용기 제조업', '증류기, 열 교환기 및 가스 발생기 제조업',
       '영상 및 음향 기기 제조업', '의료용품 및 기타 의약 관련제품 제조업', '신문 발행업',
       '항공기, 우주선 및 부품 제조업', '그 외 자동차용 신품 부품 제조업', '그 외 기타 1차 철강 제조업',
       '창작 및 예술관련 서비스업', '그 외 기타 제품 제조업', '기타 1차 비철금속 제조업',
       '그 외 기타 전문, 과학 및 기술 서비스업', '골프장 운영업', '전자 부품 실장기판 제조업', '인쇄업',
       '철강선 제조업', '화훼류 및 식물 도매업', '개인 및 가정용품 임대업', '기계장비 및 관련 물품 도매업',
       '광고 영화 및 비디오물 제작업', '주정 제조업', '전동기 및 발전기 제조업',
       '영화, 비디오물 및 방송 프로그램 제작 관련 서비스업', '골판지, 종이 상자 및 종이 용기 제조업',
       '생활용품 도매업', '기타 사행시설 관리 및 운영업', '동 압연, 압출 및 연신제품 제조업',
       '산업용 가스 제조업', '기타 대형 종합 소매업', '화장품 및 화장용품 도매업', '일반 전기 공사업',
       '플라스틱 제품 제조업', '그 외 기타 전기 통신업', '시멘트, 석회, 플라스터 및 그 제품 제조업',
       '염료, 안료 및 관련제품 도매업', '신용 조사 및 추심 대행업', '유리 및 유리제품 제조업',
       '전자코일, 변성기 및 기타 전자 유도자 제조업', '육류 가공 및 저장 처리업', '건설 및 채광용 기계장비 제조업',
       '문구용품, 회화용품, 사무용품 도매업', '염료, 조제 무기 안료, 유연제 및 기타 착색제 제조업',
       '교육 지원 서비스업', '시외버스 운송업', '혼성 및 재생 플라스틱 소재 물질 제조업',
       '일반 및 생활 숙박시설 운영업', '항공 여객 운송업', '제재 및 목재 가공업',
       '반도체 및 디스플레이 제조용 기계 제조업', '자동차용 엔진 및 자동차 제조업', '기체 연료 및 관련제품 도매업',
       '산업용 난방 보일러, 금속탱크 및 유사 용기 제조업', '콘크리트 관 및 기타 구조용 콘크리트제품 제조업',
       '기반조성 및 시설물 축조관련 전문공사업', '금속 열처리업', '플라스틱 접착처리 제품 제조업',
       '기타 운송관련 서비스업', '건축 기술, 엔지니어링 및 관련 기술 서비스업', '소주 제조업',
       '치과용 기기 제조업', '무기 및 총포탄 제조업', '그 외 기타 분류 안된 화학제품 제조업',
       '기타 도로 화물 운송업', '기타 정보 서비스업',
       '측정, 시험, 항해, 제어 및 기타 정밀 기기 제조업; 광학 기기 제외', '복합비료 및 기타 화학비료 제조업',
       '유기 발광 표시장치 제조업', '자동차 엔진용 신품 부품 제조업', '전기 공급 및 제어장치 제조업',
       '운동 및 경기용구 제조업', '기타 음향기기 제조업', '열간 압연 및 압출제품 제조업', '금속 절삭기계 제조업',
       '광고 대행업', '자동차용 신품 동력 전달장치 및 전기장치 제조업',
       '전동기, 발전기 및 전기 변환ㆍ공급ㆍ제어 장치 제조업', '건물설비 설치 공사업', '계면활성제 제조업',
       '비메모리용 및 기타 전자집적회로 제조업', '사무ㆍ상업용 및 공공기관용 건물 건설업',
       '그 외 기타 분류 안된 상품 전문 소매업', '건반 악기 제조업', '도장 및 기타 피막 처리업',
       '내연기관 제조업', '유아용 의류 도매업', '탁주 및 약주 제조업', '건물 건설업', '의복 액세서리 제조업',
       '화학섬유 제조업', '기타 섬유제품 제조업', '기관차 및 기타 철도 차량 제조업',
       '그 외 기타 분류 안된 비금속 광물제품 제조업', '의복 소매업', '바이오 연료 및 혼합물 제조업',
       '액체 여과기 제조업', '컴퓨터시설 관리업', '운송장비용 주유소 운영업', '액체 연료 및 관련제품 도매업',
       '승강기 제조업', '서적, 잡지 및 기타 인쇄물 출판업', '물질 성분 검사 및 분석업',
       '기타 화학 물질 및 화학제품 도매업', '곡물 및 유지작물 도매업', '위생용 및 산업용 도자기 제조업',
       '증기, 냉ㆍ온수 및 공기 조절 공급업', '수상 화물 취급업', '내화 요업제품 제조업',
       '고체 연료 및 관련제품 도매업', '산업용 농ㆍ축산물 및 동ㆍ식물 도매업', '주방용 전기 기기 제조업',
       '기타 전문 서비스업', '직물, 편조 원단 및 의복류 염색 가공업', '비디오 및 기타 영상 기기 제조업',
       '건축 설계 및 관련 서비스업', '그 외 기타 분류 안된 섬유제품 제조업',
       '그 외 기타 달리 분류되지 않은 제품 제조업', '살균ㆍ살충제 및 농약 제조업', '통신ㆍ방송장비 및 부품 도매업',
       '금속 캔 및 기타 포장용기 제조업', '연마재 제조업', '아스팔트 콘크리트 및 혼합제품 제조업',
       '1차 철강 제조업', '자동차용 신품 조향장치 및 현가장치 제조업', '음ㆍ식료품 및 담배 도매업',
       '기타 의료용 기기 제조업', '여신 금융업', '기타 기초 무기화학 물질 제조업', '일차전지 및 축전지 제조업',
       '그 외 기타 개인 서비스업', '톱 및 호환성 공구 제조업', '건설 및 토목공사용 기계ㆍ장비 임대업',
       '전자카드 제조업', '승용차 및 기타 여객용 자동차 제조업', '기타 기관 및 터빈 제조업',
       '주방용 및 음식점용 목재 가구 제조업', '금융 리스업', '연료 소매업',
       '시스템ㆍ응용 소프트웨어 개발 및 공급업', '기타 비철금속 압연, 압출 및 연신제품 제조업',
       '수산동물 훈제, 조리 및 유사 조제식품 제조업', '기타 게임 소프트웨어 개발 및 공급업', '항공기용 부품 제조업',
       '기타 신발 제조업', '의료용 기구 소매업', '체인화 편의점', '기타 반도체 소자 제조업', '원유 정제처리업',
       '자동차 판매업', '가금류 가공 및 저장 처리업', '자동차 부품 및 내장품 판매업', '주철관 제조업',
       '비주거용 건물 개발 및 공급업', '귀금속 및 장신용품 제조업', '직원 훈련기관', '주류 도매업',
       '플라스틱 필름 제조업', '강화 및 재생 목재 제조업', '무기 안료용 금속 산화물 및 관련 제품 제조업',
       '무점포 소매업', '기타 과학기술 서비스업', '전기업', '편조 원단 제조업',
       '건물 및 토목 엔지니어링 서비스업', '용기 세척, 포장 및 충전기 제조업', '그 외 기타 플라스틱 제품 제조업',
       '절삭 가공 및 유사 처리업', '광고업', '육상 여객 운송업', '광섬유 케이블 제조업',
       '유인 항공기, 항공 우주선 및 보조장치 제조업', '그 외 기타 가구 제조업', '산업용 유리 제조업',
       '물질 검사, 측정 및 분석 기구 제조업', '산업용 냉장 및 냉동장비 제조업', '물리, 화학 및 생물학 연구개발업',
       '증권 발행, 관리, 보관 및 거래 지원 서비스업', '가죽, 가방 및 유사 제품 제조업', '금속 위생용품 제조업',
       '가죽의복 제조업', '기타 비알코올 음료 제조업', '표면 가공목재 및 특정 목적용 제재목 제조업',
       '자동차 차체용 신품 부품 제조업', '자동차용 신품 동력 전달장치 제조업', '시각 디자인업',
       '설치용 및 위생용 플라스틱제품 제조업', '생활용 가구 도매업', '콜센터 및 텔레마케팅 서비스업',
       '수산물 가공 및 저장 처리업', '합성고무 및 플라스틱 물질 제조업', '음ㆍ식료품 및 담배 소매업',
       '과실, 채소 가공 및 저장 처리업', '그 외 기타 분류 안된 전문, 과학 및 기술 서비스업',
       '자연과학 연구개발업', '기금 운영업', '고무제품 제조업', '그 외 기타 봉제의복 제조업', '자동차 임대업',
       '그 외 기타 운송장비 제조업', '도축, 육류 가공 및 저장 처리업', '전문 디자인업', '통신장비 수리업',
       '그 외 기타 운송관련 서비스업', '가구 소매업', '전기 통신업', '비주거용 건물 건설업',
       '중고 자동차 판매업', '선박 및 보트 건조업', '기타 가공 공작기계 제조업',
       '기타 산업용 기계 및 장비 도매업', '인쇄 잉크 및 회화용 물감 제조업', '금속 가구 제조업',
       '플라스틱 발포 성형제품 제조업', '비료, 농약 및 살균ㆍ살충제 제조업', '합성고무 제조업', '가공식품 도매업',
       '동물용 사료 및 조제식품 제조업', '인쇄 및 인쇄관련 산업', '광물 처리 및 취급장비 제조업',
       '기타 비철금속 제련, 정련 및 합금 제조업', '구조용 금속제품, 탱크 및 증기발생기 제조업',
       '컴퓨터 시스템 통합 자문, 구축 및 관리업', '정형 외과용 및 신체 보정용 기기 제조업', '일반 서적 출판업',
       '인쇄 및 제책용 기계 제조업', '분사기 및 소화기 제조업', '섬유, 의복, 신발 및 가죽제품 소매업',
       '방사선 장치 및 전기식 진단 기기 제조업', '신발 소매업', '오디오물 출판 및 원판 녹음업',
       '화약 및 불꽃제품 제조업', '자동차 차체 및 트레일러 제조업', '기타 플라스틱 발포 성형제품 제조업',
       '지정 폐기물 처리업', '그 외 기타 금속 가공업', '송전 및 배전업', '전자상거래 소매업',
       '모바일 게임 소프트웨어 개발 및 공급업', '엔지니어링 서비스업', '낙농제품 및 식용 빙과류 제조업',
       '휴양 콘도 운영업', '기타 선박 건조업', '비금속광물 분쇄물 생산업', '부동산 개발 및 공급업',
       '기타 물품 취급장비 제조업', '보험 대리 및 중개업', '동물성 및 식물성 유지 제조업', '구름베어링 제조업',
       '박판, 합판 및 유사 적층판 제조업', '전기회로 개폐, 보호 장치 제조업', '의료용 가구 제조업',
       '컨베이어 장치 제조업', '접착제 및 젤라틴 제조업', '항공기용 엔진 제조업', '위생용 종이제품 제조업',
       '영화관 운영업', '기타 생활용 섬유 및 직물 제품 도매업', '도로 화물 운송업',
       '레이더, 항행용 무선 기기 및 측량 기구 제조업', '인형, 장난감 및 오락용품 제조업', '컴퓨터 프린터 제조업',
       '마그네틱 및 광학 매체 제조업', '기타 광학 기기 제조업', '자전거 및 환자용 차량 제조업', '담배제품 제조업',
       '위성 및 기타 방송업', '기술 시험, 검사 및 분석업', '육류 도매업', '산업 생산시설 종합 건설업',
       '재보험업', '유압 기기 제조업', '슈퍼마켓', '플라스틱 시트 및 판 제조업', '그 외 기타 정보 서비스업',
       '시장 조사 및 여론 조사업', '연 및 아연 제련, 정련 및 합금 제조업',
       '유선 온라인 게임 소프트웨어 개발 및 공급업', '기타 식품 제조업', '부동산관련 서비스업',
       '자전거 및 기타 운송장비 도매업', '여행사 및 기타 여행 보조 서비스업',
       '그 외 기타 창작 및 예술관련 서비스업', '기타 생활용품 소매업', '차체 및 특장차 제조업',
       '그 외 기타 생활용품 도매업', '보증보험업', '건설 폐기물 처리업', '기타 기술 및 직업 훈련학원',
       '기타 상품 전문 소매업', '절연선 및 케이블 제조업', '변압기 제조업', '가구 제조업',
       '맥아 및 맥주 제조업', '가전제품 소매업', '자연과학 및 공학 융합 연구개발업', '기체 여과기 제조업',
       '기타 항공 운송지원 서비스업', '항공기, 우주선 및 보조장치 제조업', '초등 교육기관',
       '컴퓨터 프로그래밍 서비스업', '곡물 가공품, 전분 및 전분제품 제조업',
       '가정용 비전기식 조리 및 난방 기구 제조업', '그 외 기타 광고 관련 서비스업', '음식점업',
       '컴퓨터 및 사무용 기계ㆍ장비 임대업', '건축용 플라스틱제품 제조업', '신발 및 신발 부분품 제조업',
       '고무 의류 및 기타 위생용 비경화 고무제품 제조업', '콘크리트, 레미콘 및 기타 시멘트, 플라스터 제품 제조업',
       '도금, 착색 및 기타 표면 처리 강재 제조업', '자동차 재제조 부품 제조업', '석회 및 플라스터 제조업',
       '기체 펌프 및 압축기 제조업', '금속 주조업', '의복 액세서리 및 모조 장신구 도매업', '프로그램 공급업',
       '보안 시스템 서비스업', '초등학교', '한의약품 제조업', '건축 자재, 철물 및 난방장치 도매업',
       '광학 렌즈 및 광학 요소 제조업', '기타 인쇄물 출판업', '해체, 선별 및 원료 재생업'], dtype=object)

In [13]:
stocked_list_with_induty_code.to_excel("stocked_list_with_induty_name.xlsx")